import os

akc = [
    (1, "French Bulldog", "french-bulldog"),
    (2, "Labrador Retriever", "labrador-retriever"),
    (3, "Golden Retriever", "golden-retriever"),
    (4, "German Shepherd Dog", "german-shepherd"),
    (5, "Dachshund", "dachshund"),
    (6, "Poodle", "poodle"),
    (7, "Beagle", "beagle"),
    (8, "Rottweiler", "rottweiler"),
    (9, "German Shorthaired Pointer", "german-shorthaired-pointer"),
    (10, "Bulldog", "bulldog"),
    (11, "Cane Corso", "cane-corso"),
    (12, "Cavalier King Charles Spaniel", "cavalier-king-charles"),
    (13, "Yorkshire Terrier", "yorkshire-terrier"),
    (14, "Australian Shepherd", "australian-shepherd"),
    (15, "Doberman Pinscher", "doberman-pinscher"),
    (16, "Pembroke Welsh Corgi", "corgi"),
    (17, "Miniature Schnauzer", "miniature-schnauzer"),
    (18, "Boxer", "boxer"),
    (19, "Pomeranian", "pomeranian"),
    (20, "Bernese Mountain Dog", "bernese-mountain-dog"),
    (21, "Shih Tzu", "shih-tzu"),
    (22, "Great Dane", "great-dane"),
    (23, "Boston Terrier", "boston-terrier"),
    (24, "Chihuahua", "chihuahua"),
    (25, "Havanese", "havanese"),
    (26, "Border Collie", "border-collie"),
    (27, "English Springer Spaniel", "english-springer-spaniel"),
    (28, "Miniature American Shepherd", "miniature-american-shepherd"),
    (29, "Shetland Sheepdog", "shetland-sheepdog"),
    (30, "Siberian Husky", "siberian-husky"),
    (31, "Brittany", "brittany"),
    (32, "Belgian Malinois", "belgian-malinois"),
    (33, "Cocker Spaniel", "cocker-spaniel"),
    (34, "Basset Hound", "basset-hound"),
    (35, "English Cocker Spaniel", "english-cocker-spaniel"),
    (36, "Vizsla", "vizsla"),
    (37, "Maltese", "maltese"),
    (38, "Pug", "pug"),
    (39, "Collie", "collie"),
    (40, "Mastiff", "mastiff"),
    (41, "Rhodesian Ridgeback", "rhodesian-ridgeback"),
    (42, "Papillon", "papillon"),
    (43, "Portuguese Water Dog", "portuguese-water-dog"),
    (44, "Shiba Inu", "shiba-inu"),
    (45, "West Highland White Terrier", "west-highland-white-terrier"),
    (46, "Newfoundland", "newfoundland"),
    (47, "Australian Cattle Dog", "australian-cattle-dog"),
    (48, "Whippet", "whippet"),
    (49, "Bichon Frise", "bichon-frise"),
    (50, "Dalmatian", "dalmatian"),
    (51, "Wirehaired Pointing Griffon", "wirehaired-pointing-griffon"),
    (52, "Giant Schnauzer", "giant-schnauzer"),
    (53, "Italian Greyhound", "italian-greyhound"),
    (54, "Weimaraner", "weimaraner"),
    (55, "Samoyed", "samoyed"),
    (56, "Chesapeake Bay Retriever", "chesapeake-bay-retriever"),
    (57, "Scottish Terrier", "scottish-terrier"),
    (58, "German Wirehaired Pointer", "german-wirehaired-pointer"),
    (59, "Bloodhound", "bloodhound"),
    (60, "Russell Terrier", "russell-terrier"),
    (61, "Staffordshire Bull Terrier", "staffordshire-bull-terrier"),
    (62, "Akita", "akita"),
    (63, "Saint Bernard", "saint-bernard"),
    (64, "Boykin Spaniel", "boykin-spaniel"),
    (65, "Cardigan Welsh Corgi", "cardigan-welsh-corgi"),
    (66, "Great Pyrenees", "great-pyrenees"),
    (67, "Miniature Pinscher", "miniature-pinscher"),
    (68, "Cairn Terrier", "cairn-terrier"),
    (69, "Nova Scotia Duck Tolling Retriever", "nova-scotia-duck-tolling-retriever"),
    (70, "Airedale Terrier", "airedale-terrier"),
    (71, "Greater Swiss Mountain Dog", "greater-swiss-mountain-dog"),
    (72, "Chinese Crested", "chinese-crested"),
    (73, "Irish Setter", "irish-setter"),
    (74, "Biewer Terrier", "biewer-terrier"),
    (75, "Irish Wolfhound", "irish-wolfhound"),
    (76, "Soft Coated Wheaten Terrier", "soft-coated-wheaten-terrier"),
    (77, "Lagotto Romagnolo", "lagotto-romagnolo"),
    (78, "Bullmastiff", "bullmastiff"),
    (79, "Coton de Tulear", "coton-de-tulear"),
    (80, "Chinese Shar-Pei", "chinese-shar-pei"),
    (81, "Alaskan Malamute", "alaskan-malamute"),
    (82, "Brussels Griffon", "brussels-griffon"),
    (83, "Lhasa Apso", "lhasa-apso"),
    (84, "Rat Terrier", "rat-terrier"),
    (85, "Keeshond", "keeshond"),
    (86, "Bull Terrier", "bull-terrier"),
    (87, "Old English Sheepdog", "old-english-sheepdog"),
    (88, "Anatolian Shepherd Dog", "anatolian-shepherd-dog"),
    (89, "English Setter", "english-setter"),
    (90, "Pekingese", "pekingese"),
    (91, "Border Terrier", "border-terrier"),
    (92, "Basenji", "basenji"),
    (93, "Standard Schnauzer", "standard-schnauzer"),
    (94, "Chow Chow", "chow-chow"),
    (95, "Dogue de Bordeaux", "dogue-de-bordeaux"),
    (96, "Leonberger", "leonberger"),
    (97, "American Staffordshire Terrier", "american-staffordshire-terrier"),
    (98, "Flat-Coated Retriever", "flat-coated-retriever"),
    (99, "Borzoi", "borzoi"),
    (100, "Bouvier des Flandres", "bouvier-des-flandres"),
    (101, "Dogo Argentino", "dogo-argentino"),
    (102, "Beauceron", "beauceron"),
    (103, "Japanese Chin", "japanese-chin"),
    (104, "Gordon Setter", "gordon-setter"),
    (105, "Miniature Bull Terrier", "miniature-bull-terrier"),
    (106, "Toy Fox Terrier", "toy-fox-terrier"),
    (107, "Wire Fox Terrier", "wire-fox-terrier"),
    (108, "American Hairless Terrier", "american-hairless-terrier"),
    (109, "Norwich Terrier", "norwich-terrier"),
    (110, "Schipperke", "schipperke"),
    (111, "Pointer", "pointer"),
    (112, "Boerboel", "boerboel"),
    (113, "Spinone Italiano", "spinone-italiano"),
    (114, "Welsh Terrier", "welsh-terrier"),
    (115, "Belgian Tervuren", "belgian-tervuren"),
    (116, "Silky Terrier", "silky-terrier"),
    (117, "Afghan Hound", "afghan-hound"),
    (118, "Tibetan Terrier", "tibetan-terrier"),
    (119, "Neapolitan Mastiff", "neapolitan-mastiff"),
    (120, "Belgian Sheepdog", "belgian-sheepdog"),
    (121, "Parson Russell Terrier", "parson-russell-terrier"),
    (122, "Tibetan Spaniel", "tibetan-spaniel"),
    (123, "Xoloitzcuintli", "xoloitzcuintli"),
    (124, "American Eskimo Dog", "american-eskimo-dog"),
    (125, "Mudi", "mudi"),
    (126, "Norfolk Terrier", "norfolk-terrier"),
    (127, "Finnish Lapphund", "finnish-lapphund"),
    (128, "Norwegian Elkhound", "norwegian-elkhound"),
    (129, "Barbet", "barbet"),
    (130, "Wirehaired Vizsla", "wirehaired-vizsla"),
    (131, "Manchester Terrier", "manchester-terrier"),
    (132, "Bluetick Coonhound", "bluetick-coonhound"),
    (133, "Clumber Spaniel", "clumber-spaniel"),
    (134, "English Toy Spaniel", "english-toy-spaniel"),
    (135, "Saluki", "saluki"),
    (136, "Bracco Italiano", "bracco-italiano"),
    (137, "Black and Tan Coonhound", "black-and-tan-coonhound"),
    (138, "Icelandic Sheepdog", "icelandic-sheepdog"),
    (139, "German Pinscher", "german-pinscher"),
    (140, "Bearded Collie", "bearded-collie"),
    (141, "Welsh Springer Spaniel", "welsh-springer-spaniel"),
    (142, "Tibetan Mastiff", "tibetan-mastiff"),
    (143, "Treeing Walker Coonhound", "treeing-walker-coonhound"),
    (144, "Smooth Fox Terrier", "smooth-fox-terrier"),
    (145, "Russian Toy", "russian-toy"),
    (146, "Redbone Coonhound", "redbone-coonhound"),
    (147, "Bedlington Terrier", "bedlington-terrier"),
    (148, "Field Spaniel", "field-spaniel"),
    (149, "Irish Terrier", "irish-terrier"),
    (150, "Australian Terrier", "australian-terrier"),
    (151, "Greyhound", "greyhound"),
    (152, "Swedish Vallhund", "swedish-vallhund"),
    (153, "Affenpinscher", "affenpinscher"),
    (154, "Black Russian Terrier", "black-russian-terrier"),
    (155, "Kerry Blue Terrier", "kerry-blue-terrier"),
    (156, "Scottish Deerhound", "scottish-deerhound"),
    (157, "Lakeland Terrier", "lakeland-terrier"),
    (158, "Nederlandse Kooikerhondje", "nederlandse-kooikerhondje"),
    (159, "Lowchen", "lowchen"),
    (160, "Pumi", "pumi"),
    (161, "Petit Basset Griffon Vendeen", "petit-basset-griffon-vendeen"),
    (162, "Irish Red and White Setter", "irish-red-and-white-setter"),
    (163, "Sealyham Terrier", "sealyham-terrier"),
    (164, "Portuguese Podengo Pequeno", "portuguese-podengo-pequeno"),
    (165, "Glen of Imaal Terrier", "glen-of-imaal-terrier"),
    (166, "Berger Picard", "berger-picard"),
    (167, "Spanish Water Dog", "spanish-water-dog"),
    (168, "Curly-Coated Retriever", "curly-coated-retriever"),
    (169, "Irish Water Spaniel", "irish-water-spaniel"),
    (170, "Danish-Swedish Farmdog", "danish-swedish-farmdog"),
    (171, "Plott Hound", "plott-hound"),
    (172, "Briard", "briard"),
    (173, "Norwegian Buhund", "norwegian-buhund"),
    (174, "Ibizan Hound", "ibizan-hound"),
    (175, "Sussex Spaniel", "sussex-spaniel"),
    (176, "American Water Spaniel", "american-water-spaniel"),
    (177, "Puli", "puli"),
    (178, "Entlebucher Mountain Dog", "entlebucher-mountain-dog"),
    (179, "Kuvasz", "kuvasz"),
    (180, "Pharaoh Hound", "pharaoh-hound"),
    (181, "Skye Terrier", "skye-terrier"),
    (182, "American English Coonhound", "american-english-coonhound"),
    (183, "Bergamasco Sheepdog", "bergamasco-sheepdog"),
    (184, "Cirneco dell Etna", "cirneco-dell-etna"),
    (185, "Komondor", "komondor"),
    (186, "Dandie Dinmont Terrier", "dandie-dinmont-terrier"),
    (187, "English Foxhound", "english-foxhound"),
    (188, "American Foxhound", "american-foxhound"),
    (189, "Otterhound", "otterhound"),
    (190, "Lancashire Heeler", "lancashire-heeler"),
    (191, "Pyrenean Shepherd", "pyrenean-shepherd"),
    (192, "Polish Lowland Sheepdog", "polish-lowland-sheepdog"),
    (193, "Canaan Dog", "canaan-dog"),
    (194, "Finnish Spitz", "finnish-spitz"),
    (195, "Azawakh", "azawakh"),
    (196, "Belgian Laekenois", "belgian-laekenois"),
    (197, "Cesky Terrier", "cesky-terrier"),
    (198, "Chinook", "chinook"),
    (199, "Harrier", "harrier"),
    (200, "Grand Basset Griffon Vendeen", "grand-basset-griffon-vendeen"),
    (201, "Sloughi", "sloughi"),
    (202, "Norwegian Lundehund", "norwegian-lundehund"),
]

folder = "C:/Pet Website/breeds/"
existing = set(os.listdir(folder))

print("=== MISSING FROM FOLDER (need new HTML file) ===")
missing = []
for rank, name, slug in akc:
    fname = slug + ".html"
    if fname not in existing:
        print(f"  AKC #{rank}: {name} -> {fname}")
        missing.append((rank, name, slug))

print(f"\nTotal missing: {len(missing)}")

# Also check which have index cards
with open("C:/Pet Website/breeds/index.html", "r", encoding="utf-8") as f:
    index_content = f.read()

print("\n=== MISSING FROM INDEX CARDS (file exists but no card) ===")
missing_card = []
for rank, name, slug in akc:
    fname = slug + ".html"
    if fname in existing and ('href="' + fname + '"') not in index_content:
        print(f"  AKC #{rank}: {name} -> {fname}")
        missing_card.append((rank, name, slug))

print(f"\nTotal missing cards: {len(missing_card)}")
