/**
 * Fills in empty 毛发类型 values in all Chinese breed HTML pages.
 * Run: node fill_coat_types.js
 */
const fs = require('fs');
const path = require('path');

// Breed slug → Chinese coat type description
const COAT_MAP = {
  'affenpinscher': '粗硬蓬松被毛，外层刚硬',
  'affenpoo': '卷毛或波浪毛，低掉毛量',
  'afghan-hound': '长而丝滑的华丽被毛',
  'airedale-terrier': '硬质双层被毛，外层刚硬，底层柔软',
  'airedoodle': '卷毛或波浪毛，低掉毛量',
  'akita-shepherd': '浓密双层被毛，季节性大量掉毛',
  'akita': '浓密、直而硬的双层被毛',
  'alaskan-malamute': '厚实双层被毛，外层粗糙，底层油脂密实',
  'american-english-coonhound': '短而硬的密实被毛',
  'american-eskimo-dog': '浓密白色双层被毛，内层厚实',
  'american-foxhound': '短而硬的密实被毛',
  'american-hairless-terrier': '无毛或极短细毛',
  'american-staffordshire-terrier': '短而硬的密实光滑被毛',
  'american-water-spaniel': '卷毛或波浪状油性被毛，防水',
  'anatolian-shepherd-dog': '短至中等长度浓密双层被毛',
  'aussiedoodle': '波浪毛或卷毛，低掉毛量',
  'aussiedor': '短至中等长度被毛，略有波浪',
  'australian-cattle-dog': '短而硬的双层被毛，防水耐候',
  'australian-shepherd': '中等长度双层被毛，直或略带波浪',
  'australian-terrier': '粗糙双层被毛，外层刚硬，底层柔软',
  'azawakh': '极短而精细的单层被毛',
  'bagel-hound': '短而密实的光滑被毛',
  'barbet': '浓密卷毛，低掉毛量',
  'basenji': '极短而精细的光滑被毛',
  'bassador': '短而密实的光滑被毛',
  'basset-hound': '短而密实，光滑，易打理',
  'beabull': '短而密实的光滑被毛',
  'beagador': '短而密实的光滑被毛',
  'beagle': '短而密实，耐候性强',
  'beaglier': '短而密实的光滑被毛',
  'bearded-collie': '长而蓬松的双层被毛',
  'beauceron': '短而硬的双层被毛，紧贴身体',
  'bedlington-terrier': '蓬松卷毛，质地如羊毛，低掉毛量',
  'belgian-laekenois': '粗糙刚硬被毛，略带波浪',
  'belgian-malinois': '短、直、硬的双层被毛',
  'belgian-sheepdog': '长而直的黑色双层被毛',
  'belgian-tervuren': '长而直或轻微波浪的双层被毛',
  'bergamasco-sheepdog': '独特的毡状分层结块被毛',
  'berger-picard': '粗糙刚硬的中等长度被毛',
  'bernedoodle': '波浪毛或卷毛，浓密，低掉毛量',
  'bernese-mountain-dog': '厚实、中等长度、略带波浪的双层被毛',
  'bichon-frise': '柔软蓬松的卷毛双层被毛，低掉毛量',
  'biewer-terrier': '长而丝滑、飘逸的被毛',
  'black-and-tan-coonhound': '短而硬的密实被毛',
  'black-russian-terrier': '粗糙浓密的波浪或卷曲被毛',
  'bloodhound': '短而硬的密实被毛',
  'bluetick-coonhound': '短而硬的密实被毛',
  'boerboel': '短而硬的密实光滑被毛',
  'borador': '短至中等长度被毛',
  'border-collie': '中等长度粗糙或光滑双层被毛',
  'border-terrier': '粗糙刚硬的双层被毛',
  'bordoodle': '卷毛或波浪毛，低掉毛量',
  'borzoi': '长而丝滑、略带波浪的被毛',
  'bossipoo': '卷毛或波浪毛，低掉毛量',
  'boston-terrier': '短毛，光滑，细腻单层被毛',
  'bouvier-des-flandres': '粗糙浓密的双层被毛',
  'boxador': '短而密实的光滑被毛',
  'boxer': '短毛光滑，紧贴身体',
  'boxerdoodle': '卷毛或波浪毛，低掉毛量',
  'boykin-spaniel': '中等长度卷毛或波浪毛，防水',
  'bracco-italiano': '短而硬的密实光滑被毛',
  'briard': '长而粗糙的波浪状双层被毛',
  'brittany': '中等长度波浪或平直被毛',
  'brussels-griffon': '粗糙刚硬被毛或短而光滑被毛',
  'bugg': '短而密实的光滑被毛',
  'bull-terrier': '短而平整的硬质被毛',
  'bullador': '短而密实的光滑被毛',
  'bulldog': '短毛，光滑，质地细腻',
  'bullmastiff': '短而硬的密实被毛',
  'cairn-terrier': '粗糙刚硬的外层被毛，柔软底层',
  'cairnoodle': '卷毛或波浪毛，低掉毛量',
  'canaan-dog': '中等长度直而硬的双层被毛',
  'cane-corso': '短、密、粗糙的双层被毛',
  'cardigan-welsh-corgi': '中等长度双层被毛，质地较硬',
  'cavalier-king-charles': '丝滑，中等长度，有羽饰',
  'cavachon': '卷毛或波浪毛，低掉毛量',
  'cavapoo': '波浪毛或卷毛，柔软，低掉毛量',
  'cavapoochon': '卷毛或波浪毛，低掉毛量',
  'cesky-terrier': '柔软波浪状被毛，质地独特',
  'cheagle': '短而密实的光滑被毛',
  'chesapeake-bay-retriever': '厚而油腻的卷毛，极佳防水性',
  'chihuahua': '短而光滑或长而柔软的被毛',
  'chinese-crested': '无毛（皮肤柔软光滑）或有粉扑型（长而丝滑）',
  'chinese-shar-pei': '极短而硬的刚毛',
  'chinook': '厚实的中等长度双层被毛',
  'chipoo': '卷毛或波浪毛，低掉毛量',
  'chiweenie': '短而平滑被毛',
  'chow-chow': '浓密粗糙双层被毛或光滑短毛',
  'chow-shepherd': '浓密双层被毛',
  'chug': '短而密实的光滑被毛',
  'chusky': '厚实浓密的双层被毛',
  'cirneco-dell-etna': '短而细腻的光滑被毛',
  'clumber-spaniel': '平直浓密丝滑的被毛，有羽饰',
  'cockapoo': '波浪毛或卷毛，柔软，低掉毛量',
  'cocker-spaniel': '中等长度丝滑被毛，有羽饰',
  'collie': '长而浓密的双层被毛，颈部有丰厚项圈',
  'corgi': '中等长度双层被毛，防水',
  'corgidor': '短至中等长度双层被毛',
  'corgipoo': '卷毛或波浪毛，低掉毛量',
  'corman-shepherd': '中等长度双层被毛',
  'coton-de-tulear': '柔软蓬松的棉絮状被毛，低掉毛量',
  'curly-coated-retriever': '紧密卷毛，防水，掉毛量少',
  'dachshund': '短光滑毛、长毛或刚毛（三种被毛类型）',
  'dalmadoodle': '卷毛或波浪毛，低掉毛量',
  'dalmatian': '短、密、质地细腻',
  'dandie-dinmont-terrier': '柔软丝状与硬毛混合的蓬松被毛',
  'danish-swedish-farmdog': '短而光滑的密实被毛',
  'doberdoodle': '卷毛或波浪毛，低掉毛量',
  'doberman-pinscher': '短毛光滑，紧贴身体',
  'dogo-argentino': '短而光滑的单层白色被毛',
  'dogue-de-bordeaux': '短而细腻的密实被毛',
  'dorgi': '短至中等长度双层被毛',
  'double-doodle': '卷毛或波浪毛，低掉毛量',
  'doxiepoo': '卷毛或波浪毛，低掉毛量',
  'english-cocker-spaniel': '中等长度丝滑被毛，有羽饰',
  'english-foxhound': '短而硬的密实被毛',
  'english-setter': '中等长度，平直丝滑，有羽饰',
  'english-springer-spaniel': '中等长度，平直或略带波浪，防水',
  'english-toy-spaniel': '中等长度丝滑被毛，有羽饰',
  'entlebucher-mountain-dog': '短而硬的密实三色被毛',
  'field-spaniel': '中等长度丝滑被毛，略带波浪',
  'finnish-lapphund': '厚而直的双层被毛，底层浓密',
  'finnish-spitz': '中等长度浓密双层被毛',
  'flandoodle': '卷毛或波浪毛，低掉毛量',
  'flat-coated-retriever': '中等长度光滑亮泽被毛，防水',
  'foodle': '卷毛或波浪毛，低掉毛量',
  'frenchton': '短而密实的光滑被毛',
  'froodle': '卷毛或波浪毛，低掉毛量',
  'gerberian-shepsky': '浓密双层被毛，季节性大量掉毛',
  'german-pinscher': '短而硬的密实光滑被毛',
  'german-shepherd': '中等长度双层被毛，防水耐候',
  'german-wirehaired-pointer': '粗糙、刚硬的防水被毛',
  'giant-schnauzer': '粗糙刚硬外层被毛，柔软底层',
  'glen-of-imaal-terrier': '中等长度粗糙硬质被毛',
  'goberian': '浓密双层被毛，季节性掉毛',
  'goldador': '短至中等长度密实被毛',
  'golden-mountain-dog': '浓密中等长度被毛，略带波浪',
  'golden-retriever': '中等长度波浪或直发双层被毛',
  'gollie': '中等至长度被毛，略带波浪',
  'gordon-setter': '中等长度，光亮，略带波浪，有羽饰',
  'goldmaraner': '短至中等长度密实被毛',
  'grand-basset-griffon-vendeen': '粗糙硬质被毛，略带波浪',
  'great-dane': '短而密实的光滑被毛',
  'great-danoodle': '卷毛或波浪毛，低掉毛量',
  'great-pyrenees': '厚实的长双层被毛，防水',
  'greater-swiss-mountain-dog': '短而浓密的三色双层被毛',
  'greyhound': '极短而细腻的光滑单层被毛',
  'harrier': '短而硬的密实被毛',
  'havapoo': '卷毛或波浪毛，低掉毛量',
  'horgi': '中等长度浓密双层被毛',
  'huskimo': '浓密厚实的双层被毛',
  'huskydoodle': '波浪毛或卷毛，低掉毛量',
  'husky-inu': '浓密双层被毛，季节性掉毛',
  'ibizan-hound': '短而光滑或粗硬的被毛',
  'icelandic-sheepdog': '中等或长度浓密双层被毛',
  'irish-doodle': '卷毛或波浪毛，低掉毛量',
  'irish-red-and-white-setter': '中等长度，平直丝滑，有羽饰',
  'irish-setter': '中等长度，丝滑光亮，有羽饰',
  'irish-terrier': '硬质密实双层被毛，刚硬而耐候',
  'irish-water-spaniel': '浓密紧实的卷毛，防水',
  'irish-wolfadoodle': '卷毛或波浪毛，低掉毛量',
  'irish-wolfhound': '粗糙硬质被毛，略带波浪',
  'italian-greyhound': '极短而细腻的光滑单层被毛',
  'jackadoodle': '卷毛或波浪毛，低掉毛量',
  'japanese-chin': '丝滑、柔软的长被毛',
  'jug': '短而密实的光滑被毛',
  'keeshond': '浓密蓬松的双层被毛，颈部有丰厚项圈',
  'kerry-blue-terrier': '柔软波浪状蓝灰色被毛，低掉毛量',
  'komondor': '独特的白色绳状毡状被毛',
  'kuvasz': '厚实的白色双层被毛，直或略带波浪',
  'labmaraner': '短而密实的光滑被毛',
  'labsky': '短至中等长度密实被毛',
  'lagotto-romagnolo': '浓密紧实的卷毛，低掉毛量',
  'lakeland-terrier': '硬质双层被毛，外层刚硬，底层柔软',
  'lancashire-heeler': '短而硬的密实黑棕被毛',
  'leonberger': '中等长度柔软双层被毛，颈部有丰厚鬃毛',
  'lhasa-apso': '长而浓密、直且质地细腻的被毛',
  'lhasapoo': '卷毛或波浪毛，低掉毛量',
  'lowchen': '长而丝滑，略带波浪的被毛',
  'maltichon': '柔软蓬松的被毛，低掉毛量',
  'manchester-terrier': '短而硬的密实光滑被毛',
  'malshi': '柔软丝滑的长被毛，低掉毛量',
  'mastiff': '短而硬的密实被毛',
  'mastidoodle': '卷毛或波浪毛，低掉毛量',
  'miniature-american-shepherd': '中等长度双层被毛，直或略带波浪',
  'miniature-bull-terrier': '短而平整的硬质被毛',
  'miniature-pinscher': '短而硬的密实光滑被毛',
  'morkie': '柔软丝滑的长被毛',
  'mudi': '卷毛或波浪状防水被毛',
  'neapolitan-mastiff': '短而硬的密实被毛，皮肤宽松多褶',
  'nederlandse-kooikerhondje': '中等长度，光滑或略带波浪，有羽饰',
  'newfiedoodle': '卷毛或波浪毛，低掉毛量',
  'norfolk-terrier': '粗糙硬质双层被毛，有倒伏的毛发',
  'norwegian-buhund': '中等长度浓密双层被毛',
  'norwegian-elkhound': '浓密厚实的银灰色双层被毛',
  'norwegian-lundehund': '浓密双层被毛，短而硬',
  'norwich-terrier': '粗糙硬质双层被毛，直立耳',
  'nova-scotia-duck-tolling-retriever': '中等长度双层防水被毛',
  'old-english-sheepdog': '厚实、蓬松、略带波浪的双层被毛',
  'otterhound': '粗糙硬质双层被毛，防水',
  'papillon': '长而丝滑，略带波浪，无底层绒毛',
  'parson-russell-terrier': '粗糙硬质或光滑短毛',
  'peekapoo': '卷毛或波浪毛，低掉毛量',
  'pekingese': '长而浓密的双层被毛，内层浓厚',
  'petit-basset-griffon-vendeen': '粗糙硬质被毛，略带波浪',
  'pharaoh-hound': '短而光滑的细腻被毛',
  'pitsky': '短至中等长度被毛，略有厚度',
  'plott-hound': '短而硬的密实被毛',
  'pointer': '短而硬的密实光滑被毛',
  'polish-lowland-sheepdog': '长而浓密、略带波浪的双层被毛',
  'pom-a-pug': '短至中等长度柔软被毛',
  'pomapoo': '卷毛或波浪毛，低掉毛量',
  'pomchi': '长而蓬松的双层被毛',
  'poochon': '卷毛或波浪毛，低掉毛量',
  'pooton': '卷毛或波浪毛，低掉毛量',
  'portidoodle': '卷毛或波浪毛，低掉毛量',
  'portuguese-podengo-pequeno': '短而光滑或粗硬的被毛',
  'portuguese-water-dog': '浓密卷毛或波浪毛，低掉毛量',
  'pugapoo': '短至中等长度柔软被毛',
  'puggle': '短而密实的光滑被毛',
  'pug': '短而光滑，细腻，双层被毛',
  'puli': '独特的绳状或毡状编结被毛',
  'pumi': '螺旋卷曲的中等长度被毛',
  'pyredoodle': '卷毛或波浪毛，低掉毛量',
  'pyrenean-shepherd': '粗糙硬质或半长被毛',
  'rat-terrier': '短而光滑的密实被毛',
  'ratoodle': '卷毛或波浪毛，低掉毛量',
  'redbone-coonhound': '短而硬的密实被毛',
  'rhodesian-ridgeback': '短而硬、密实的光滑被毛，脊背有独特脊线',
  'rottador': '短而密实的光滑被毛',
  'rottsky': '浓密双层被毛，季节性掉毛',
  'rottle': '卷毛或波浪毛，低掉毛量',
  'russell-terrier': '粗糙硬质或光滑短毛',
  'russian-toy': '短而光滑或长而丝滑的被毛',
  'saint-berdoodle': '卷毛或波浪毛，低掉毛量',
  'saint-bernard': '短而密实或长而波浪状的厚实双层被毛',
  'saluki': '丝滑光滑的短毛，耳部和尾部有羽饰',
  'sammypoo': '卷毛或波浪毛，低掉毛量',
  'samoyed': '厚实蓬松的白色双层被毛',
  'schipperke': '浓密、粗糙的双层被毛，颈部有项圈',
  'scoodle': '卷毛或波浪毛，低掉毛量',
  'scottish-deerhound': '粗糙硬质被毛，略带波浪',
  'scottish-terrier': '硬质外层被毛，浓密柔软底层',
  'sealyham-terrier': '硬质粗糙外层被毛，浓密底层',
  'sheepadoodle': '卷毛或波浪毛，低掉毛量',
  'shepadoodle': '卷毛或波浪毛，低掉毛量',
  'sheprador': '短至中等长度密实被毛',
  'shiba-inu': '浓密双层被毛，外层刚直，底层柔软',
  'shih-poo': '卷毛或波浪毛，低掉毛量',
  'silky-terrier': '长而丝滑、有光泽的被毛',
  'skye-terrier': '长而直、硬而厚的被毛，遮盖全身',
  'sloughi': '短而细腻的光滑单层被毛',
  'smooth-fox-terrier': '短而平整的硬质光滑被毛',
  'soft-coated-wheaten-terrier': '柔软丝状的波浪被毛，低掉毛量',
  'spanish-water-dog': '卷毛，可自然形成绳状',
  'spinone-italiano': '粗糙硬质被毛，有胡须和眉毛',
  'spoodle': '卷毛或波浪毛，低掉毛量',
  'springerdoodle': '卷毛或波浪毛，低掉毛量',
  'staffordshire-bull-terrier': '短而硬的密实光滑被毛',
  'standard-schnauzer': '硬质双层被毛，外层刚硬，底层柔软',
  'sussex-spaniel': '平直柔软的被毛，有羽饰',
  'swedish-vallhund': '中等长度浓密双层被毛',
  'tibetan-mastiff': '厚实、浓密的双层被毛',
  'tibetan-spaniel': '中等长度丝滑双层被毛',
  'tibetan-terrier': '长而直或波浪状的浓密双层被毛',
  'toy-fox-terrier': '短而光滑的精细被毛',
  'treeing-walker-coonhound': '短而硬的密实被毛',
  'vizsla': '短而密实，光滑的单层被毛',
  'weimaraner': '短而密实，光滑的单层被毛',
  'weimardoodle': '卷毛或波浪毛，低掉毛量',
  'welsh-springer-spaniel': '平直丝滑的密实被毛，有羽饰',
  'welsh-terrier': '硬质双层被毛，外层刚硬，底层柔软',
  'west-highland-white-terrier': '硬质白色外层被毛，浓密底层',
  'westiepoo': '卷毛或波浪毛，低掉毛量',
  'whippet': '短而细腻的光滑单层被毛',
  'whoodle': '柔软波浪或卷曲被毛，低掉毛量',
  'wire-fox-terrier': '硬质刚硬的双层被毛',
  'wirehaired-pointing-griffon': '粗糙硬质防水被毛，有胡须',
  'wirehaired-vizsla': '粗糙硬质被毛，防水耐候',
  'woodle': '卷毛或波浪毛，低掉毛量',
  'xoloitzcuintli': '无毛（皮肤光滑）或极短毛',
};

const zhDir = path.join(__dirname, 'zh', 'breeds');
const files = fs.readdirSync(zhDir).filter(f => f.endsWith('.html') && f !== 'index.html');

let updated = 0;
let skipped = 0;
let notFound = [];

for (const file of files) {
  const slug = file.replace('.html', '');
  const coatZh = COAT_MAP[slug];

  if (!coatZh) {
    notFound.push(slug);
    continue;
  }

  const filePath = path.join(zhDir, file);
  const html = fs.readFileSync(filePath, 'utf8');

  const emptyPattern = '<div class="info-box-label">毛发类型</div><div class="info-box-value"></div>';
  if (!html.includes(emptyPattern)) {
    skipped++;
    continue;
  }

  const filled = html.replace(
    emptyPattern,
    `<div class="info-box-label">毛发类型</div><div class="info-box-value">${coatZh}</div>`
  );

  fs.writeFileSync(filePath, filled, 'utf8');
  updated++;
}

console.log(`Updated: ${updated}, Skipped (already filled): ${skipped}, No map entry: ${notFound.length}`);
if (notFound.length) console.log('Missing from map:', notFound.join(', '));
