/**
 * Inserts 别名 into the 快速概览 sidebar for pages that are missing it.
 * Also updates existing 别名 values that are still in English.
 * Run: node insert_aliases.js
 */
const fs = require('fs');
const path = require('path');

const ALIAS_MAP = {
  'affenpinscher': '猴子梗, 猴脸犬',
  'affenpoo': '非凡贵宾犬',
  'afghan-hound': '阿富汗猎犬, 阿富汗',
  'airedale-terrier': '梗犬之王, 水边梗',
  'airedoodle': '艾尔代尔贵宾犬',
  'akita-shepherd': '秋田牧羊混血',
  'akita': '秋田犬',
  'alaskan-malamute': '阿拉斯加犬, 马拉穆特',
  'american-english-coonhound': '英式浣熊猎犬, 红斑浣熊猎犬',
  'american-eskimo-dog': '爱斯基摩犬, Eskie',
  'american-foxhound': '弗吉尼亚猎狐犬, 美式猎犬',
  'american-hairless-terrier': 'AHT',
  'american-staffordshire-terrier': 'AmStaff, 美国斯塔福德梗',
  'american-water-spaniel': 'AWS, 美国水猎犬',
  'anatolian-shepherd-dog': '康加尔牧羊犬, 土耳其牧羊犬',
  'aussiedoodle': '澳式贵宾犬, 澳牧贵宾',
  'aussiedor': '澳牧拉多',
  'australian-cattle-dog': '蓝色跟腱犬, 红色跟腱犬, 昆士兰跟腱犬, ACD',
  'australian-shepherd': '澳牧',
  'australian-terrier': '澳梗',
  'azawakh': 'Idi, Hanshee（非洲原名）',
  'bagel-hound': '比格巴吉度混血',
  'barbet': '法国水猎犬',
  'basenji': '非洲无吠犬, 刚果犬',
  'bassador': '巴吉度拉多',
  'basset-hound': '巴吉度',
  'beabull': '比格斗牛混血',
  'beagador': '比格拉多',
  'beagle': '英国比格犬, 猎兔犬',
  'beaglier': '比格骑士混血',
  'bearded-collie': '有胡须的柯利, Beardie',
  'beauceron': '博斯牧羊犬, 法国短毛牧羊犬',
  'bedlington-terrier': '贝灵顿梗, 羊羔犬',
  'belgian-laekenois': '拉肯诺斯犬, 比利时麻布被毛牧羊犬',
  'belgian-malinois': '马里诺斯犬',
  'belgian-sheepdog': '格罗恩达尔犬, 比利时黑色长毛牧羊犬',
  'belgian-tervuren': '特伏丹犬, 比利时长毛牧羊犬',
  'bergamasco-sheepdog': '贝加马斯科牧羊犬',
  'berger-picard': '皮卡第牧羊犬',
  'bernedoodle': '伯恩山贵宾犬',
  'bernese-mountain-dog': '伯纳犬, Berner Sennenhund',
  'bichon-frise': '卷毛比雄犬, 特内里费犬',
  'biewer-terrier': 'Biewer约克夏梗',
  'black-and-tan-coonhound': 'B&T, 美国黑褐浣熊猎犬',
  'black-russian-terrier': '黑珍珠, 俄罗斯黑色梗犬',
  'bloodhound': '寻血猎犬',
  'bluetick-coonhound': '蓝斑浣熊猎犬',
  'boerboel': '南非獒犬, 布尔犬',
  'borador': '博德拉多犬',
  'border-collie': '苏格兰牧羊犬, 博德柯利',
  'border-terrier': 'BT, 科克代尔梗',
  'bordoodle': '边牧贵宾犬',
  'borzoi': '俄国猎狼犬, 俄国灵缇',
  'bossipoo': '波士顿贵宾混血',
  'boston-terrier': '美国绅士',
  'bouvier-des-flandres': '比利时牧牛犬',
  'boxador': '拳师拉多犬',
  'boxer': '拳师犬',
  'boxerdoodle': '拳师贵宾犬',
  'boykin-spaniel': '博伊金猎鸟犬, 南卡罗来纳州犬',
  'bracco-italiano': '意大利指示犬',
  'briard': '法国长毛牧羊犬',
  'brittany': '布列塔尼猎鸟犬',
  'brussels-griffon': '布鲁塞尔格里芬犬',
  'bugg': '波士顿巴哥混血',
  'bull-terrier': '斗牛梗, 英国斗牛梗',
  'bullador': '斗牛拉多犬',
  'bulldog': '英国斗牛犬',
  'bullmastiff': '猎场看守犬, 斗牛獒',
  'cairn-terrier': '凯恩梗',
  'cairnoodle': '凯恩贵宾犬',
  'canaan-dog': '以色列国犬',
  'cane-corso': '意大利獒犬, Cane Corso Italiano',
  'cardigan-welsh-corgi': '卡狄根柯基, CWC',
  'cavalier-king-charles': '骑士查理王犬, CKCS',
  'cavachon': '骑士双飞犬',
  'cavapoo': '骑士贵宾犬, Cavoodle',
  'cavapoochon': '骑士贵宾双飞混血',
  'cesky-terrier': '波西米亚梗, 捷克梗',
  'cheagle': '吉娃娃比格混血',
  'chesapeake-bay-retriever': '切萨皮克湾寻回犬, Chessie',
  'chihuahua': '吉娃娃, Chi',
  'chinese-crested': '冠毛犬, 粉扑犬',
  'chinese-shar-pei': '沙皮犬',
  'chinook': '美国雪橇犬',
  'chipoo': '吉娃娃贵宾犬',
  'chiweenie': '吉娃娃腊肠混血',
  'chow-chow': '松狮犬, 唐犬',
  'chow-shepherd': '松狮牧羊混血',
  'chug': '吉娃娃巴哥混血',
  'chusky': '松狮哈士奇混血',
  'cirneco-dell-etna': '西西里灵缇',
  'clumber-spaniel': '克伦伯猎鸟犬',
  'cockapoo': '可卡贵宾犬',
  'cocker-spaniel': '可卡犬',
  'collie': '粗毛柯利, 灵犬莱西',
  'corgi': '彭布罗克柯基, 威尔士柯基',
  'corgidor': '柯基拉多混血',
  'corgipoo': '柯基贵宾混血',
  'corman-shepherd': '柯基德牧混血',
  'coton-de-tulear': '棉花犬, 马达加斯加皇家犬',
  'curly-coated-retriever': '卷毛寻回犬, CCR',
  'dachshund': '腊肠犬, 香肠犬',
  'dalmadoodle': '斑点贵宾犬',
  'dalmatian': '马车犬, 斑点犬',
  'dandie-dinmont-terrier': '丹迪·丁蒙梗',
  'danish-swedish-farmdog': '丹麦瑞典农场犬',
  'doberdoodle': '杜宾贵宾犬',
  'doberman-pinscher': '杜宾犬, Dobie',
  'dogo-argentino': '阿根廷獒犬',
  'dogue-de-bordeaux': '法国獒犬, 波尔多斗牛犬',
  'dorgi': '腊肠柯基混血',
  'double-doodle': '双拼贵宾犬',
  'doxiepoo': '腊肠贵宾混血',
  'english-cocker-spaniel': '英国可卡犬, ECS',
  'english-foxhound': '英国猎狐犬',
  'english-setter': '英国雪达犬',
  'english-springer-spaniel': '史宾格犬, ESS',
  'english-toy-spaniel': '查理王猎鸟犬',
  'entlebucher-mountain-dog': '恩特雷布赫山地犬',
  'field-spaniel': '田野猎鸟犬',
  'finnish-lapphund': '芬兰拉普猎犬',
  'finnish-spitz': '芬兰猎鸟犬, Finkie',
  'flandoodle': '弗兰德贵宾犬',
  'flat-coated-retriever': '平毛寻回犬',
  'foodle': '猎狐梗贵宾混血',
  'frenchton': '法斗波士顿混血',
  'french-bulldog': '法斗',
  'froodle': '法斗贵宾混血',
  'gerberian-shepsky': '德牧哈士奇混血',
  'german-pinscher': '德国宾沙犬',
  'german-shepherd': 'GSD, 阿尔萨斯犬',
  'german-shorthaired-pointer': 'GSP, 德国短毛指示犬',
  'german-wirehaired-pointer': 'GWP, 德国钢毛指示犬',
  'giant-schnauzer': '巨型雪纳瑞',
  'glen-of-imaal-terrier': '格伦梗, 爱尔兰格伦梗',
  'goberian': '金毛哈士奇混血',
  'goldador': '金毛拉多混血',
  'golden-mountain-dog': '金毛伯恩山混血',
  'golden-retriever': '金毛寻回犬, 金毛',
  'gollie': '金毛柯利混血',
  'goldendoodle': '黄金贵宾犬, Groodle',
  'gordon-setter': '戈登雪达犬',
  'goldmaraner': '金毛威玛混血',
  'grand-basset-griffon-vendeen': '大格里芬旺代巴吉度, GBGV',
  'great-dane': '大丹犬, 犬中阿波罗',
  'great-danoodle': '大丹贵宾混血',
  'great-pyrenees': '大白熊犬, 比利牛斯山犬',
  'greater-swiss-mountain-dog': '大瑞士山地犬, Swissie',
  'greyhound': '灵缇犬',
  'harrier': '哈利犬, 野兔猎犬',
  'havapoo': '哈瓦那贵宾混血',
  'havanese': '哈瓦那犬',
  'horgi': '哈士奇柯基混血',
  'huskimo': '哈士奇爱斯基摩混血',
  'huskydoodle': '哈士奇贵宾混血',
  'husky-inu': '哈士奇柴犬混血',
  'ibizan-hound': '伊比沙猎犬',
  'icelandic-sheepdog': '冰岛牧羊犬',
  'irish-doodle': '爱尔兰雪达贵宾混血',
  'irish-red-and-white-setter': '爱尔兰红白雪达犬',
  'irish-setter': '爱尔兰雪达犬',
  'irish-terrier': '爱尔兰梗',
  'irish-water-spaniel': '爱尔兰水猎犬, IWS',
  'irish-wolfadoodle': '爱尔兰猎狼贵宾混血',
  'irish-wolfhound': '爱尔兰猎狼犬',
  'italian-greyhound': '意大利灵缇, IG',
  'jackadoodle': '杰克罗素贵宾混血',
  'japanese-chin': '狆, 日本狆犬',
  'jug': '杰克罗素巴哥混血',
  'keeshond': '荷兰狮毛犬',
  'kerry-blue-terrier': '凯利蓝梗, 爱尔兰蓝梗',
  'komondor': '科蒙多尔犬, 匈牙利绳状毛犬',
  'kuvasz': '匈牙利库瓦兹犬',
  'labmaraner': '拉多威玛混血',
  'labsky': '拉多哈士奇混血',
  'labradoodle': '拉布拉多贵宾犬',
  'labrador-retriever': '拉布拉多犬',
  'lagotto-romagnolo': '罗马涅水猎犬, 意大利松露犬',
  'lakeland-terrier': '莱克兰梗',
  'lancashire-heeler': '兰开夏跟腱犬',
  'leonberger': '莱昂贝格犬',
  'lhasa-apso': '拉萨阿普索, 西藏圣犬',
  'lhasapoo': '拉萨贵宾混血',
  'lowchen': '小狮子犬',
  'maltichon': '马耳他双飞混血',
  'manchester-terrier': '黑褐梗, 绅士梗',
  'malshi': '马耳他西施混血',
  'maltese': '马耳他犬',
  'maltipoo': '马耳他贵宾犬',
  'mastiff': '英国獒犬',
  'mastidoodle': '獒犬贵宾混血',
  'miniature-american-shepherd': '迷你澳牧, MAS',
  'miniature-bull-terrier': '迷你斗牛梗',
  'miniature-pinscher': '迷你宾沙犬, Min Pin',
  'miniature-schnauzer': '迷你雪纳瑞',
  'morkie': '马耳他约克夏混血',
  'mudi': '匈牙利穆迪犬',
  'neapolitan-mastiff': '那不勒斯獒犬',
  'nederlandse-kooikerhondje': '荷兰诱鸭猎鸟犬',
  'newfiedoodle': '纽芬兰贵宾混血',
  'newfoundland': '纽芬兰犬, 温柔巨犬',
  'norfolk-terrier': '诺福克梗',
  'norwegian-buhund': '挪威布哈德犬',
  'norwegian-elkhound': '挪威猎麋犬',
  'norwegian-lundehund': '海雀犬',
  'norwich-terrier': '诺里奇梗',
  'nova-scotia-duck-tolling-retriever': '托勒犬, NSDR',
  'old-english-sheepdog': '古英格兰牧羊犬, OES',
  'otterhound': '水獭猎犬',
  'papillon': '蝴蝶犬',
  'parson-russell-terrier': '帕森罗素梗',
  'peekapoo': '北京贵宾混血',
  'pekingese': '北京犬, 京巴',
  'petit-basset-griffon-vendeen': '小格里芬旺代巴吉度, PBGV',
  'pharaoh-hound': '法老猎犬',
  'pitsky': '比特斗牛哈士奇混血',
  'plott-hound': '普洛特猎犬',
  'pointer': '英国指示犬',
  'polish-lowland-sheepdog': '波兰低地牧羊犬, PON',
  'pom-a-pug': '博美巴哥混血',
  'pomapoo': '博美贵宾混血',
  'pomchi': '博美吉娃娃混血',
  'poochon': '贵宾双飞混血',
  'pooton': '贵宾棉花混血',
  'portidoodle': '葡萄牙水犬贵宾混血',
  'pomsky': '博美哈士奇混血',
  'pomeranian': '博美犬',
  'poodle': '贵宾犬, Caniche',
  'portuguese-podengo-pequeno': '葡萄牙小波登格犬',
  'portuguese-water-dog': '葡萄牙水犬, PWD',
  'pugapoo': '巴哥贵宾混血',
  'puggle': '巴哥比格混血',
  'pug': '巴哥犬',
  'puli': '普利犬',
  'pumi': '匈牙利普米犬',
  'pyredoodle': '大白熊贵宾混血',
  'pyrenean-shepherd': '比利牛斯牧羊犬',
  'rat-terrier': '鼠梗',
  'ratoodle': '鼠梗贵宾混血',
  'redbone-coonhound': '红骨猎浣熊犬',
  'rhodesian-ridgeback': '罗得西亚脊背犬, 狮子猎犬',
  'rottador': '罗威纳拉多混血',
  'rottsky': '罗威纳哈士奇混血',
  'rottweiler': '罗威纳犬, Rottie',
  'rottle': '罗威纳贵宾混血',
  'russell-terrier': '杰克罗素梗',
  'russian-toy': '俄罗斯玩具梗',
  'saint-berdoodle': '圣伯纳贵宾混血',
  'saint-bernard': '圣伯纳犬, 阿尔卑斯救援犬',
  'saluki': '萨路基猎犬, 皇家猎犬',
  'sammypoo': '萨摩贵宾混血',
  'samoyed': '萨摩耶犬, 微笑天使',
  'schipperke': '小船长犬',
  'schnoodle': '雪纳瑞贵宾混血',
  'scottish-deerhound': '苏格兰猎鹿犬',
  'scottish-terrier': '苏格兰梗, Scottie',
  'scoodle': '苏格兰梗贵宾混血',
  'sealyham-terrier': '西利汉梗',
  'sheepadoodle': '英国牧羊贵宾混血',
  'shepadoodle': '德牧贵宾混血',
  'sheprador': '德牧拉多混血',
  'shetland-sheepdog': '设德兰牧羊犬, Sheltie',
  'shiba-inu': '柴犬',
  'shih-poo': '西施贵宾混血',
  'shih-tzu': '西施犬, 狮子犬',
  'shorkie': '绍基犬',
  'siberian-husky': '哈士奇',
  'silky-terrier': '澳大利亚丝毛梗',
  'skye-terrier': '史凯梗',
  'sloughi': '阿拉伯灵缇',
  'smooth-fox-terrier': '光滑短毛猎狐梗',
  'soft-coated-wheaten-terrier': '爱尔兰软毛梗',
  'spanish-water-dog': '西班牙水犬',
  'spinone-italiano': '意大利格里芬犬',
  'spoodle': '英可卡贵宾混血',
  'springerdoodle': '史宾格贵宾混血',
  'staffordshire-bull-terrier': '斯塔福德斗牛梗, Staffy',
  'standard-schnauzer': '标准雪纳瑞',
  'sussex-spaniel': '苏塞克斯猎鸟犬',
  'swedish-vallhund': '瑞典牧牛犬, 维京犬',
  'tibetan-mastiff': '藏獒',
  'tibetan-spaniel': '西藏猎鸟犬',
  'tibetan-terrier': '藏梗, 西藏圣犬',
  'toy-fox-terrier': '玩具猎狐梗',
  'treeing-walker-coonhound': '沃克浣熊猎犬',
  'vizsla': '匈牙利指示犬',
  'weimaraner': '灰色幽灵, 威玛猎犬',
  'weimardoodle': '威玛贵宾混血',
  'welsh-springer-spaniel': '威尔士史宾格犬',
  'welsh-terrier': '威尔士梗',
  'west-highland-white-terrier': '西高地白梗, Westie',
  'westiepoo': '西高地贵宾混血',
  'whippet': '惠比特犬',
  'whoodle': '软毛梗贵宾混血',
  'wire-fox-terrier': '刚毛猎狐梗',
  'wirehaired-pointing-griffon': '钢毛格里芬指示犬',
  'wirehaired-vizsla': '钢毛维斯拉犬',
  'woodle': '威尔士梗贵宾混血',
  'xoloitzcuintli': '墨西哥无毛犬, Xolo',
  'yorkipoo': '约克夏贵宾混血',
  'yorkshire-terrier': '约克夏梗, Yorkie',
};

const zhDir = path.join(__dirname, 'zh', 'breeds');
const files = fs.readdirSync(zhDir).filter(f => f.endsWith('.html') && f !== 'index.html');

let updated = 0;
let inserted = 0;
let notFound = [];

// Pattern to match existing 别名 box (replace its value) — global flag to replace all occurrences
const existingPat = /<div class="info-box-label">别名<\/div><div class="info-box-value">([^<]*)<\/div>/g;

// Pattern to insert before: the 体型 info-box in sidebar
const insertBefore = '<div class="info-box" style="margin-top:8px"><div class="info-box-label">体型</div>';

for (const file of files) {
  const slug = file.replace('.html', '');
  const aliasZh = ALIAS_MAP[slug];

  if (!aliasZh) {
    notFound.push(slug);
    continue;
  }

  const filePath = path.join(zhDir, file);
  let html = fs.readFileSync(filePath, 'utf8');

  if (html.includes('别名')) {
    // Update existing alias value
    const newHtml = html.replace(
      existingPat,
      `<div class="info-box-label">别名</div><div class="info-box-value">${aliasZh}</div>`
    );
    if (newHtml !== html) {
      fs.writeFileSync(filePath, newHtml, 'utf8');
      updated++;
    }
  } else if (html.includes(insertBefore)) {
    // Insert alias box before 体型 in sidebar
    const aliasBox = `<div class="info-box" style="margin-top:8px"><div class="info-box-label">别名</div><div class="info-box-value">${aliasZh}</div></div>\n          `;
    const newHtml = html.replace(insertBefore, aliasBox + insertBefore);
    fs.writeFileSync(filePath, newHtml, 'utf8');
    inserted++;
  }
}

console.log(`Updated existing: ${updated}, Inserted new: ${inserted}, No map entry: ${notFound.length}`);
if (notFound.length) console.log('Missing:', notFound.join(', '));
