const fs=require('fs'), path=require('path');
const R=[
  ['Calcium for small-breed bone health','钙质支持小型犬骨骼健康'],
  ['Joint supplements from middle age benefit this large, active working dog\'s long-term soundness','中年后补充关节营养素有益于这一大型活跃工作犬的长期健康'],
  ['Feed twice daily and avoid vigorous exercise before and after meals to reduce bloat risk','每天两餐，进餐前后避免剧烈运动以降低胃扩张风险'],
  ['Feed twice daily to avoid bloat risk','每天两餐以避免胃扩张风险'],
  ['大型犬-breed formula with quality protein for this substantial working hound','优质蛋白质大型犬配方适合这一强壮的工作猎犬'],
  ['Always feed two meals — never one large meal for this deep-chested, bloat-susceptible breed','始终每天两餐——绝不一次性大量喂食这一深胸、易患胃扩张的犬种'],
  ['大型犬/giant breed formula prevents over-rapid bone growth in puppies','大型犬/巨型犬配方防止幼犬过快的骨骼生长'],
  ['Feed twice daily — never once — to reduce bloat risk in this deep-chested breed','每天两餐——绝不一次喂食——以降低这一深胸犬种的胃扩张风险'],
  ['Feed twice daily — never once — to reduce bloat risk','每天两餐——绝不一次喂食——以降低胃扩张风险'],
  ['Glucosamine and chondroitin from middle age for joint support','中年后补充葡萄糖胺和软骨素支持关节健康'],
  ['高-protein, large-breed formula supports their muscular, working-dog frame','高蛋白大型犬配方支持其肌肉发达的工作犬体型'],
  ['Feed twice daily on a schedule to support energy levels in this consistently active small breed','按时每天两餐以支持这一持续活跃小型犬种的能量水平'],
  ['高-quality protein from real meat sources supports lean muscle','来自真实肉类的优质蛋白质支持精瘦肌肉'],
  ['每天两餐，进餐前后限制运动以降低胃扩张风险 in this deep-chested large breed','每天两餐，进餐前后限制运动以降低这一深胸大型犬的胃扩张风险'],
  ['高-quality protein supports their athletic, working-dog muscle mass','优质蛋白质支持其运动型工作犬肌肉'],
  ['高-quality protein supports the Brittany\'s lean athletic build and hunting endurance','优质蛋白质支持布列塔尼猎鸟犬的精瘦运动体型和狩猎耐力'],
  ['Avoid foods with common allergens (wheat, corn, soy, dairy) — Bulldogs have some of the highest food allergy and skin sensitivity rates of any breed','避免含常见过敏原（小麦、玉米、大豆、乳制品）的食物——斗牛犬是食物过敏和皮肤敏感率最高的犬种之一'],
  ['小型犬-breed or medium kibble pieces — their flat face and undershot jaw make it difficult to pick up large pieces','小型犬或中型颗粒狗粮——其扁平面部和下颌突出使其难以拾起大颗粒'],
  ['Feed twice daily from floor level — raised bowls may increase bloat risk in deep-chested large breeds','在地板高度每天两餐喂食——高脚碗可能增加深胸大型犬的胃扩张风险'],
  ['Glucosamine &amp; chondroitin for joint support as they age','随着年龄增长，补充葡萄糖胺和软骨素支持关节健康'],
  ['高-quality protein supports the athletic desert dog physique','优质蛋白质支持运动型沙漠犬体型'],
  ['大型犬-breed formula with quality protein supports their working sled-dog build','优质蛋白质大型犬配方支持其工作雪橇犬体型'],
  ['多种 small meals for puppies to prevent hypoglycemia','幼犬多次小份喂食以预防低血糖'],
  ['高-quality protein first ingredient for lean muscle','优质蛋白质作为首要成分，促进精瘦肌肉发育'],
  ['Dental health kibble to manage crowding-related tooth decay','牙齿健康狗粮管理因拥挤引起的龋齿'],
  ['高-quality protein maintains lean, light muscle mass typical of the sighthound build','优质蛋白质维持视觉猎犬体型特有的精瘦、轻盈肌肉'],
  ['高-quality protein supports energy for their playful, social lifestyle','优质蛋白质为其活泼、爱社交的生活方式提供能量'],
  ['小型犬-breed formula with appropriate kibble size for their proportions','适合其体型比例颗粒大小的小型犬配方'],
  ['Joint support for agile dog','关节支持适合敏捷型犬只'],
  ['高-quality protein supports lean muscle for this active sporting breed','优质蛋白质支持这一活跃运动型犬种的精瘦肌肉'],
  ['Glucosamine for joint health','葡萄糖胺支持关节健康'],
  ['小型犬-breed kibble or small pieces — their flat face makes picking up large kibble difficult','小型犬颗粒狗粮或小块食物——其扁平面部使拾起大颗粒困难'],
  ['大型犬幼犬配方 — controls growth rate to protect developing hips and elbows','大型犬幼犬配方——控制生长速度以保护发育中的髋关节和肘关节'],
  ['Glucosamine and chondroitin for joint support — both parents are hip dysplasia risks','葡萄糖胺和软骨素支持关节健康——双亲犬种均有髋关节发育不良风险'],
  ['Two meals daily to reduce bloat risk','每天两餐降低胃扩张风险'],
  ['Glucosamine &amp; chondroitin — essential for a breed prone to hip dysplasia','葡萄糖胺和软骨素——对易患髋关节发育不良的犬种至关重要'],
  ['Feed two meals daily — never one large meal for this bloat-susceptible breed','每天两餐——绝不一次性大量喂食这一易患胃扩张的犬种'],
  ['关节补充剂 useful for this energetic, low-slung breed','关节补充剂对这一精力旺盛、矮腿犬种有益'],
  ['Split meals into two servings and avoid strenuous exercise before and after eating to reduce GDV risk','将食物分成两份，进食前后避免剧烈运动，以降低GDV风险'],
  ['高-protein formula supports lean muscle mass in this athletic breed','高蛋白配方支持这一运动型犬种的精瘦肌肉'],
  ['小型犬 or toy-breed formula for appropriate portion sizing','小型犬或玩具犬配方，提供适当份量'],
  ['高-quality protein formula supports muscle maintenance and working-dog metabolism','优质蛋白质配方支持肌肉维护和工作犬代谢'],
  ['Foods with glucosamine &amp; chondroitin — helps their joints as they age','含葡萄糖胺和软骨素的食物——随着年龄增长有助于关节健康'],
  ['高蛋白质适合活跃的梗犬 lifestyle','高蛋白质适合活跃的梗犬生活方式'],
  ['高-quality protein maintains the Manchester\'s athletic, lean muscle mass','优质蛋白质维持曼彻斯特梗运动型、精瘦的肌肉'],
  ['高-protein, quality formula supports their muscular build and energy levels','高蛋白优质配方支持其肌肉体型和能量水平'],
  ['多种 small meals to prevent hypoglycemia in puppies','幼犬多次小份喂食以预防低血糖'],
  ['Dental health diet or regular tooth brushing is essential','牙齿健康饮食或定期刷牙至关重要'],
  ['高-quality protein supports lean muscle in this athletic, driven working breed','优质蛋白质支持这一运动型、有干劲工作犬种的精瘦肌肉'],
  ['小型犬-to-medium breed formula at an appropriate life stage','适合生命阶段的小中型犬配方'],
  ['高 protein for an active small terrier','高蛋白质适合活跃的小型梗犬'],
  ['Two meals daily is ideal rather than free-feeding','每天两餐是理想选择，而非自由取食'],
  ['高-quality protein supports their active, hunting-dog metabolism','优质蛋白质支持其活跃的猎犬代谢'],
  ['高-quality protein maintains their lean, athletic sighthound build','优质蛋白质维持其精瘦、运动型视觉猎犬体型'],
  ['高-protein, medium-breed formula suits their active hunting-dog metabolism','高蛋白中型犬配方适合其活跃的猎犬代谢'],
  ['Split into 每天2餐 minimum to reduce bloat risk — never feed one large meal','每天至少2餐以降低胃扩张风险——绝不一次性大量喂食'],
  ['小型犬-breed formula appropriate for their size and metabolism','适合其体型和代谢的小型犬配方'],
  ['Monitor weight — they can gain easily if exercise drops off','监控体重——如果运动量减少容易增重'],
  ['Monitor weight carefully — a lean body condition is essential for agility and herding performance','仔细监控体重——精瘦体型对敏捷和牧羊表现至关重要'],
  ['Feed two meals daily to reduce bloat risk for this deep-chested breed','每天两餐以降低这一深胸犬种的胃扩张风险'],
  ['Monitor weight carefully — Redbones can put on weight quickly if exercise decreases','仔细监控体重——运动量减少时红骨猎浣熊犬可能迅速增重'],
  ['小型犬-breed formula sized for tiny jaws','专为小嘴设计大小的小型犬配方'],
  ['Dental health kibble or regular brushing — flat face causes dental crowding','牙齿健康狗粮或定期刷牙——扁平面部导致牙齿拥挤'],
  ['高-quality small-breed kibble supports their fast metabolism','优质小型犬颗粒狗粮支持其快速代谢'],
  ['Antioxidants for overall health','抗氧化剂支持整体健康'],
  ['The beard and mustache trap food — clean after meals to prevent odor and skin irritation in the facial hair','胡须和髭须会沾染食物——进餐后清洁以防止面部毛发的异味和皮肤刺激'],
  ['Monitor weight carefully — the dense coat can disguise weight gain until it\'s significant','仔细监控体重——浓密的被毛可能掩盖体重增加直到变得显著'],
  ['高-quality protein supports lean muscle for this athletic herding breed','优质蛋白质支持这一运动型牧羊犬种的精瘦肌肉'],
  ['Feed two meals daily — never one large meal for this deep-chested breed','每天两餐——绝不一次性大量喂食这一深胸犬种'],
  ['高-quality protein supports their lean, athletic muscle mass','优质蛋白质支持其精瘦、运动型肌肉'],
  ['高-quality protein supports their muscular terrier build','优质蛋白质支持其肌肉发达的梗犬体型'],
  ['Dental health matters — missing teeth (linked to hairless gene) affect chewing; choose appropriate food texture','牙齿健康很重要——缺牙（与无毛基因相关）影响咀嚼；选择适当的食物质地'],
  ['高-protein active formula — Huskies are efficient metabolizers but Huskydoodles are more active than Huskies alone','高蛋白活力配方——哈士奇代谢效率高，但哈士奇贵宾混血比纯哈士奇更活跃'],
];

const zhDir=path.join(__dirname,'zh','breeds');
const files=fs.readdirSync(zhDir).filter(f=>f.endsWith('.html')&&f!=='index.html');
let total=0,changed=0;
for(const file of files){
  const fp=path.join(zhDir,file);
  let h=fs.readFileSync(fp,'utf8');
  const orig=h;
  for(const [en,zh] of R){ if(h.includes(en)){ h=h.split(en).join(zh); total++; } }
  if(h!==orig){ fs.writeFileSync(fp,h,'utf8'); changed++; }
}
console.log('Files changed:',changed,'Replacements:',total);
