/**
 * Step 2: Translate remaining English diet and cost bullet points.
 * Run: node translate_diet.js
 */
const fs = require('fs');
const path = require('path');

const REPLACEMENTS = [
  // ── Partial Chinese prefix + English suffix patterns ──────────────────────
  ['高-protein diet supports the Airedale\'s athletic build and terrier energy demands', '高蛋白饮食支持艾尔代尔梗的运动体型和梗犬的高能量需求'],
  ['高-quality protein formula supports the lean, athletic working hound physique', '优质蛋白质配方支持精瘦、健硕的工作猎犬体型'],
  ['高-quality protein maintains their athletic hunting physique', '优质蛋白质维持其运动型狩猎体型'],
  ['高-protein, moderate-fat formula supports muscle maintenance', '高蛋白、适量脂肪配方支持肌肉维护'],
  ['高-quality protein for an active small dog', '优质蛋白质适合活跃的小型犬'],
  ['高-quality protein — the Azawakh\'s muscles are the most visible feature of their body', '优质蛋白质——阿扎瓦克犬的肌肉是其最显著的外形特征'],
  ['高-protein, limited-ingredient diet suits the Basenji\'s primitive, high-metabolism physique', '高蛋白、有限配料饮食适合巴辛吉犬原始、高代谢的体质'],
  ['高-fiber foods help them feel fuller longer — important for this notoriously food-obsessed breed', '高纤维食物让它们更长时间保持饱腹感——对于这个出了名贪吃的犬种尤为重要'],
  ['高 protein for herding activity levels', '高蛋白质适应牧羊犬的活动水平'],
  ['高-protein diet supports the Beauceron\'s working drive and substantial lean muscle mass', '高蛋白饮食支持博斯牧羊犬的工作动力和强健的瘦肌肉'],
  ['高-protein diet (28%+) supports working muscle mass', '高蛋白饮食（28%以上）支持工作犬的肌肉质量'],
  ['高-quality protein supports their lean, athletic mountain-dog physique', '优质蛋白质支持其精瘦、健壮的山地犬体型'],
  ['高-quality protein supports their active, working-dog physique', '优质蛋白质支持其活跃的工作犬体型'],
  ['高-quality protein (chicken, beef, or fish) as the first ingredient — Boxers are muscular and need real meat to maintain their build', '优质蛋白质（鸡肉、牛肉或鱼肉）作为首要成分——拳师犬肌肉发达，需要真正的肉类来维持体型'],
  ['高-protein active formula to fuel their energetic lifestyle', '高蛋白活力配方为其充满活力的生活方式提供能量'],
  ['高-quality protein supports their athletic, hunting-dog build', '优质蛋白质支持其运动型猎犬体型'],
  ['高-protein formula (26%+ protein) to support their athletic, muscular build', '高蛋白配方（26%以上蛋白质）支持其运动型、肌肉发达的体型'],
  ['高-quality protein fuels the 超大型犬 Schnauzer\'s working drive and substantial muscle mass', '优质蛋白质为巨型雪纳瑞的工作动力和强健肌肉提供能量'],
  ['高-quality protein formula supports their dense, muscular working-terrier build', '优质蛋白质配方支持其浓密、肌肉发达的工作梗犬体型'],
  ['高-quality protein for lean muscle', '优质蛋白质促进瘦肌肉发育'],
  ['高-quality protein fuels the Toller\'s intense athleticism and retriever working drive', '优质蛋白质为托勒犬出色的运动能力和寻回工作动力提供能量'],
  ['高-quality protein (30%+) supports lean muscle mass in this powerful working breed', '优质蛋白质（30%以上）支持这一强壮工作犬种的精瘦肌肉'],
  ['高-quality protein, large-breed formula suits their working-dog metabolism', '优质蛋白质大型犬配方适合其工作犬代谢需求'],
  ['高-quality protein maintains lean muscle for this active hunting breed', '优质蛋白质维持这一活跃猎犬的精瘦肌肉'],
  ['高-quality protein supports lean muscle for this active hunting breed', '优质蛋白质支持这一活跃猎犬的精瘦肌肉'],
  ['高-quality protein supports lean muscle in this athletic small terrier', '优质蛋白质支持这种健壮小梗犬的精瘦肌肉'],
  ['高-quality protein supports the lean muscle mass essential to this working breed\'s conformation', '优质蛋白质支持这一工作犬种体型所需的精瘦肌肉'],
  ['高-quality protein supports their active, pack-hunting physique', '优质蛋白质支持其活跃的群体狩猎体型'],
  ['高-quality protein supports the Staffie\'s dense muscle mass and active lifestyle', '优质蛋白质支持斯塔福德梗的致密肌肉和活跃生活方式'],
  ['高-quality protein supports lean muscle maintenance in this naturally muscular breed', '优质蛋白质支持这一天生肌肉发达犬种的精瘦肌肉维护'],
  ['高-quality protein supports their lean, athletic primitive-hound build', '优质蛋白质支持其精瘦、健壮的原始猎犬体型'],
  ['高-quality protein supports their muscular, athletic build', '优质蛋白质支持其肌肉发达、运动型体型'],
  ['高-quality protein supports lean muscle for this athletic, driven working breed', '优质蛋白质为这一充满活力的工作犬种提供精瘦肌肉支持'],
  ['高-quality protein for massive muscular build', '优质蛋白质适合强大的肌肉体型'],
  ['高-quality protein for muscle tone', '优质蛋白质维持肌肉张力'],
  ['高-quality protein for tiny muscles', '优质蛋白质适合小型犬的精细肌肉'],
  ['高-quality protein (chicken or fish) as the first ingredient to support their flowing coat', '优质蛋白质（鸡肉或鱼肉）作为首要成分，支持其飘逸的被毛'],
  ['高-quality protein (chicken, fish, or lamb) as the first ingredient — Huskies are athletic working dogs who thrive on real meat', '优质蛋白质（鸡肉、鱼肉或羊肉）作为首要成分——哈士奇是喜食真正肉类的运动型工作犬'],
  ['高-quality protein (chicken, fish, beef) supports lean muscle mass for this athletic breed', '优质蛋白质（鸡肉、鱼肉、牛肉）支持这一运动型犬种的精瘦肌肉'],
  ['高-quality protein (chicken, salmon, or lamb) as the first ingredient — Poodles are active and need good protein for muscle maintenance', '优质蛋白质（鸡肉、三文鱼或羊肉）作为首要成分——贵宾犬活跃好动，需要优质蛋白质维持肌肉'],
  ['高-quality protein (chicken or salmon) as the first ingredient', '优质蛋白质（鸡肉或三文鱼）作为首要成分'],
  ['高-quality small-breed formula helps maintain the coat in Powderpuffs and supports skin health in hairless varieties', '优质小型犬配方有助于维护粉扑型的被毛，并支持无毛型的皮肤健康'],
  ['高-quality, moderate-protein diet suits the Chow\'s low-energy, less-active lifestyle', '优质适量蛋白质饮食适合松狮犬低能量、少活动的生活方式'],
  ['高-quality protein supports the lean, athletic sighthound build', '优质蛋白质支持精瘦、健壮的视觉猎犬体型'],
  ['高-quality protein and fat supports the sighthound\'s lean, athletic build', '优质蛋白质和脂肪支持视觉猎犬精瘦、运动型体型'],
  ['高-quality protein supports the Welshie\'s compact, muscular terrier build and high energy level', '优质蛋白质支持威尔士梗紧凑、肌肉发达的体型和高能量水平'],
  ['高-quality protein supports sustained athletic endurance in the field', '优质蛋白质支持野外持续的运动耐力'],
  ['高-quality protein supports the Spinone\'s large frame and moderate working drive', '优质蛋白质支持意大利钢毛指示犬的大型体型和适度工作动力'],
  ['高-quality protein for active terrier build', '优质蛋白质适合活跃的梗犬体型'],
  ['高-quality protein for active terrier', '优质蛋白质适合活跃的梗犬'],
  ['高-quality protein for active terrier lifestyle', '优质蛋白质适合活跃的梗犬生活方式'],
  ['高-quality protein for working dog physique', '优质蛋白质适合工作犬体型'],
  ['高-quality protein for muscle maintenance', '优质蛋白质用于肌肉维护'],
  ['高-quality dry kibble with real meat as the first ingredient', '以真实肉类为首要成分的优质干粮'],
  ['高-quality animal protein as the first ingredient supports their muscular build', '以优质动物蛋白质为首要成分，支持其肌肉体型'],
  ['高-protein, high-activity formula to meet their caloric demands', '高蛋白、高活动量配方满足其热量需求'],
  ['高-protein, high-fat formula for active working dogs', '高蛋白、高脂肪配方适合活跃的工作犬'],
  ['高-protein working dog formula supports the GWP\'s demanding fieldwork and lean muscle mass', '工作犬高蛋白配方支持德国钢毛指示犬繁重的野外工作和精瘦肌肉'],
  ['高-energy small breed formula matches the Russell\'s extreme metabolic demands per body weight', '高能量小型犬配方匹配罗素梗每体重单位的极高代谢需求'],
  ['高-quality protein maintains their lean, athletic frame', '优质蛋白质维持其精瘦、运动型体型'],
  ['高-quality protein and fat formula for an active herding dog\'s needs', '优质蛋白质和脂肪配方满足活跃牧羊犬的需求'],
  ['高-protein formula supports their active, muscular build', '高蛋白配方支持其活跃、肌肉发达的体型'],
  ['高-protein, moderate-fat diet fuels the ACD\'s extreme working capacity and lean muscle mass', '高蛋白、适量脂肪饮食为澳洲牧牛犬的超强工作能力和精瘦肌肉提供能量'],
  ['高-protein diet supports the Belgian Sheepdog\'s athletic build and intense working drive', '高蛋白饮食支持比利时牧羊犬的运动体型和强烈的工作动力'],
  ['高-protein diet supports the Bouvier\'s working drive and substantial muscle mass', '高蛋白饮食支持弗兰德斯牧牛犬的工作动力和强健肌肉'],
  ['高-quality protein formula for an active, working-dog metabolism', '优质蛋白质配方适合活跃的工作犬代谢'],
  ['高-quality protein for an active, working-dog metabolism', '优质蛋白质适合活跃的工作犬代谢'],
  ['高-quality protein (chicken, beef, or lamb) as the first ingredient — Rotties are muscular and need real meat', '优质蛋白质（鸡肉、牛肉或羊肉）作为首要成分——罗威纳犬肌肉发达，需要真正的肉类'],
  ['高-quality protein supports the Shiba\'s ancestral hunting background and lean, muscular build', '优质蛋白质支持柴犬的狩猎传统背景和精瘦、肌肉发达的体型'],
  ['高-protein diet suits the Shiba\'s ancestral hunting background and lean, muscular build', '高蛋白饮食适合柴犬的狩猎传统背景和精瘦、肌肉发达的体型'],
  ['高-quality protein supports lean muscle for this athletic, driven working breed', '优质蛋白质支持这一有干劲的运动型工作犬种的精瘦肌肉'],
  ['高-quality protein supports lean muscle in this athletic breed', '优质蛋白质支持这一运动型犬种的精瘦肌肉'],
  ['高-quality protein supports their lean, athletic sporting-dog physique', '优质蛋白质支持其精瘦、运动型猎犬体型'],
  ['高-quality protein formula supports the GSD\'s working drive and lean muscle mass', '优质蛋白质配方支持德国牧羊犬的工作动力和精瘦肌肉'],
  ['高-quality protein as first ingredient supports their athletic build', '以优质蛋白质为首要成分，支持其运动体型'],
  ['高-quality protein keeps their muscular little body in top shape', '优质蛋白质使其肌肉发达的小身体保持最佳状态'],
  ['高-quality protein keeps their playful, active lifestyle well-fueled', '优质蛋白质为其活泼好动的生活方式提供充足能量'],
  ['高-quality protein supports their agile, working herding physique', '优质蛋白质支持其灵活、工作牧羊犬的体型'],
  ['高-quality protein supports their active, herding-dog lifestyle', '优质蛋白质支持其活跃的牧羊犬生活方式'],
  ['高-quality protein supports their muscular build and energy levels', '优质蛋白质支持其肌肉体型和能量水平'],
  ['高-quality protein supports their athletic, herding-dog build', '优质蛋白质支持其运动型牧羊犬体型'],
  ['高-quality protein supports their active, working-dog lifestyle', '优质蛋白质支持其活跃的工作犬生活方式'],
  ['高 protein content supports lean muscle mass in this exceptionally active breed', '高蛋白质含量支持这一极度活跃犬种的精瘦肌肉'],
  ['高 protein for active working dog', '高蛋白质适合活跃的工作犬'],
  ['高 protein for active herding dog', '高蛋白质适合活跃的牧羊犬'],
  ['高 protein for active herding lifestyle', '高蛋白质适合活跃的牧羊生活方式'],
  ['高 protein for active field dog', '高蛋白质适合活跃的野外犬'],
  ['高 protein for athletic field dog', '高蛋白质适合运动型野外犬'],
  ['高 protein for active small working dog', '高蛋白质适合活跃的小型工作犬'],
  ['高 protein for active terrier', '高蛋白质适合活跃的梗犬'],
  ['高 protein keeps their lean, muscular build strong', '高蛋白质保持其精瘦、肌肉发达的体型强健'],
  ['高 animal protein for muscle and endurance', '高动物蛋白质促进肌肉发育和耐力'],
  ['高 animal protein for muscle maintenance', '高动物蛋白质用于肌肉维护'],
  ['高 protein for massive muscular build', '高蛋白质适合强大的肌肉体型'],
  ['高-protein, large-breed formula supports lean muscle mass in this powerful sporting dog', '高蛋白大型犬配方支持这一强壮运动犬的精瘦肌肉'],
  ['高-large-breed formula with high-quality protein supports lean muscle mass', '大型犬高蛋白质配方支持精瘦肌肉'],

  // 低- patterns
  ['低-glycemic carbohydrates to manage diabetes risk', '低升糖指数碳水化合物，控制糖尿病风险'],
  ['低-calorie formula is ideal — even small amounts of extra weight put massive stress on their long spine', '低热量配方是理想选择——即使少量超重也会给其长脊椎造成巨大压力'],
  ['低-calorie, lean protein formula — Bulldogs gain weight easily and excess weight worsens their breathing problems dramatically', '低热量精瘦蛋白质配方——斗牛犬容易增重，超重会大幅加重其呼吸问题'],
  ['低-fat diet recommended for dogs with intestinal disease, which the Basenji is prone to', '推荐患有肠道疾病的犬只采用低脂肪饮食，巴辛吉犬易患此病'],
  ['低-copper diet critical for breed health', '低铜饮食对犬种健康至关重要'],
  ['低-sodium, heart-healthy formulas become important as Boxers age — discuss with your vet after age 5', '随着拳师犬年龄增长，低钠、心脏健康配方变得重要——5岁后请与兽医讨论'],
  ['低-calorie treats preserve calorie budget for meals', '低热量零食为正餐保留热量预算'],
  ['低 fat to maintain racing-lean build', '低脂肪维持赛跑型精瘦体型'],
  ['低 fat for lean body condition', '低脂肪维持精瘦体型'],
  ['低 fat to maintain slender build', '低脂肪维持苗条体型'],

  // 小型犬-breed patterns
  ['小型犬-breed, high-protein formula suits their terrier metabolism', '高蛋白小型犬配方适合其梗犬代谢特点'],
  ['小型犬-breed formula with high-quality protein supports the Lancashire Heeler\'s active, muscular build', '高蛋白小型犬配方支持兰开夏跟腱犬活跃、肌肉发达的体型'],
  ['小型犬-breed formula with small kibble size helps prevent gulping and aids digestion', '小颗粒小型犬配方有助于防止狼吞虎咽并促进消化'],
  ['小型犬-breed formula designed for their size and caloric needs', '专为其体型和热量需求设计的小型犬配方'],
  ['小型犬-breed formula with appropriate kibble size for their tiny mouths', '配有适合小嘴颗粒大小的小型犬配方'],
  ['小型犬-breed formula with high-quality protein suits the Cesky\'s metabolism', '高蛋白小型犬配方适合切斯基梗的代谢特点'],
  ['小型犬-breed or toy formula with smaller kibble size', '颗粒更小的小型犬或玩具犬配方'],
  ['小型犬-breed kibble size helps prevent gulping and aids digestion', '小型犬颗粒大小有助于防止狼吞虎咽并促进消化'],
  ['小型犬-breed formula provides the right caloric density for their size', '小型犬配方提供适合其体型的热量密度'],
  ['小型犬-breed formula with small kibble pieces — Shih Tzus have tiny mouths and flat faces that make large kibble hard to eat', '小颗粒小型犬配方——西施犬嘴巴小且脸部扁平，难以进食大颗粒狗粮'],
  ['小型犬-breed quality formula suits their compact body well', '优质小型犬配方非常适合其紧凑的体型'],
  ['小型犬-breed formula is appropriate given the lightweight frame', '考虑到其轻盈的体型，小型犬配方是合适的选择'],
  ['小型犬-breed formula with high-quality protein supports the Schipperke\'s active metabolism', '高蛋白小型犬配方支持斯基派克犬活跃的代谢'],
  ['小型犬-to-medium breed formula suits their size and metabolism', '适合其体型和代谢的小中型犬配方'],
  ['小型犬-to-medium breed formula suits their size and fast herding-dog metabolism', '适合其体型和快速牧羊犬代谢的小中型犬配方'],
  ['小型犬-to-medium breed formula supports the Vallhund\'s compact, active frame', '小中型犬配方支持瑞典牧牛犬紧凑、活跃的体型'],
  ['小型犬-breed formula provides appropriate caloric density for their size', '小型犬配方为其体型提供适当的热量密度'],
  ['小型犬-breed formula to match their tiny stomach size', '与其小胃容量匹配的小型犬配方'],
  ['小型犬-breed formula with small kibble size suits their tiny mouth', '小颗粒小型犬配方适合其小嘴'],
  ['小型犬-breed kibble sized for flat-faced breeds to reduce swallowing difficulty and choking risk', '专为扁脸犬种设计大小的小型犬颗粒，减少吞咽困难和噎食风险'],
  ['小型犬-breed formula supports their fast terrier metabolism', '小型犬配方支持其快速的梗犬代谢'],

  // 大型犬-breed patterns
  ['大型犬-breed formula prevents overly rapid growth in puppies, protecting developing joints', '大型犬配方防止幼犬过快生长，保护发育中的关节'],
  ['大型犬-breed formula designed for their size and caloric needs', '专为其体型和热量需求设计的大型犬配方'],
  ['大型犬-breed, high-quality protein formula suits their working-dog metabolism', '高蛋白大型犬配方适合其工作犬代谢特点'],
  ['大型犬-breed formula with high-quality protein supports lean muscle mass in this powerful sporting dog', '高蛋白大型犬配方支持这一强壮运动犬的精瘦肌肉'],
  ['大型犬-breed formula helps support joints during rapid growth', '大型犬配方在快速生长期帮助支撑关节'],
  ['大型犬-breed formula with quality protein supports lean muscle mass in this powerful working breed', '高蛋白大型犬配方支持这一强壮工作犬种的精瘦肌肉'],
  ['大型犬-breed formula supports joint development and maintenance', '大型犬配方支持关节发育和维护'],
  ['大型犬-breed formula supports healthy joint development and adult maintenance', '大型犬配方支持健康的关节发育和成犬维护'],
  ['大型犬-breed formula to support slow joint development in puppyhood', '大型犬配方支持幼犬期缓慢的关节发育'],
  ['大型犬-breed formula for puppies — controls growth rate and protects developing joints', '幼犬大型犬配方——控制生长速度，保护发育中的关节'],
  ['大型犬-breed formula with quality protein supports the Otterhound\'s working hound physique', '高蛋白大型犬配方支持水獭猎犬的工作猎犬体型'],
  ['大型犬-breed formula — controls calcium/phosphorus ratio for healthy joint development', '大型犬配方——控制钙磷比例，促进健康关节发育'],
  ['大型犬-breed formula with quality protein supports the Lancashire Heeler\'s needs', '高蛋白大型犬配方支持兰开夏跟腱犬的需求'],
  ['大型犬-breed, high-quality protein formula supports their working-hound physique', '高蛋白大型犬配方支持其工作猎犬体型'],
  ['大型犬幼犬配方 prevents too-rapid skeletal development in this enormous breed', '大型犬幼犬配方防止这一巨型犬种过快的骨骼发育'],
  ['大型犬幼犬配方 prevents too-rapid skeletal development in this powerful breed', '大型犬幼犬配方防止这一强壮犬种过快的骨骼发育'],
  ['大型犬幼犬配方 prevents too-rapid growth in this heavy breed during critical bone development', '大型犬幼犬配方防止这一重型犬种在关键骨骼发育期过快生长'],
  ['大型犬幼犬配方 prevents too-rapid growth in this heavy breed\'s developing joints and bones', '大型犬幼犬配方防止这一重型犬种发育中的关节和骨骼过快生长'],
  ['大型犬幼犬配方 prevents too-rapid growth that strains developing joints in this powerful breed', '大型犬幼犬配方防止使这一强壮犬种发育中关节承压的过快生长'],
  ['大型犬幼犬配方 limits calcium and phosphorus to slow bone growth and reduce OCD risk', '大型犬幼犬配方限制钙和磷以减缓骨骼生长，降低OCD风险'],
  ['大型犬幼犬配方 prevents too-rapid bone growth that can cause developmental joint problems', '大型犬幼犬配方防止可能导致发育性关节问题的过快骨骼生长'],
  ['大型犬幼犬配方 prevents too-rapid bone growth during the long growth phase', '大型犬幼犬配方防止漫长生长期中过快的骨骼生长'],
  ['大型犬幼犬配方 prevents too-rapid bone growth — crucial in a breed growing to over 100磅 in 18 months', '大型犬幼犬配方防止过快的骨骼生长——对于18个月内体重超过100磅的犬种至关重要'],
  ['大型犬 breed puppy formula is essential — controls bone and joint development rate', '大型犬幼犬配方至关重要——控制骨骼和关节发育速度'],
  ['大型犬 breed formula recommended during puppyhood for controlled bone growth', '幼犬期推荐使用大型犬配方以控制骨骼生长'],
  ['大型犬 breed puppy formula with controlled calcium/phosphorus ratios is essential for healthy joint development', '含受控钙磷比例的大型犬幼犬配方对健康关节发育至关重要'],
  ['大型犬/giant breed formula — prevents too-rapid growth that stresses joints', '大型犬/巨型犬配方——防止使关节承压的过快生长'],
  ['大型犬/giant-breed formula slows growth rate, protecting joints during development', '大型犬/巨型犬配方减缓生长速度，保护发育期关节'],
  ['超大型犬-breed puppy formula prevents too-rapid bone growth during the long growth phase', '超大型犬幼犬配方防止漫长生长期中过快的骨骼生长'],
  ['超大型犬-breed puppy formula is essential — too-rapid growth in a breed reaching 150–200磅 causes lasting joint damage', '超大型犬幼犬配方至关重要——体重达150–200磅的犬种过快生长会造成持久的关节损伤'],
  ['超大型犬-breed puppy formula prevents too-rapid growth that causes lifelong joint problems in this massive breed', '超大型犬幼犬配方防止在这一大型犬种中引起终身关节问题的过快生长'],
  ['超大型犬-breed formula designed for their size and caloric needs', '专为其体型和热量需求设计的超大型犬配方'],
  ['超大型犬-breed puppy formula prevents too-rapid bone growth — crucial in a breed growing to over 100磅 in 18 months', '超大型犬幼犬配方防止过快的骨骼生长——对18个月内体重超过100磅的犬种至关重要'],
  ['工作犬组 dogs guarding livestock may burn significantly more calories than sedentary pets of the same size', '从事牲畜守护工作的工作犬可能比同体型的安静宠物消耗更多热量'],
  ['工作犬组 and sport dogs may need 25–50% more calories than sedentary pets of the same size', '工作犬和运动犬可能需要比同体型安静宠物多25–50%的热量'],
  ['工作犬组 dogs on farms or in sport programs may need 25–40% more calories than sedentary pets of the same size', '在农场工作或参加运动项目的工作犬可能需要比同体型安静宠物多25–40%的热量'],
  ['工作犬组 retrievers in cold water may need 25–40% more calories on active hunting days', '在冷水中工作的工作型寻回犬在活跃狩猎日可能需要多25–40%的热量'],
  ['工作犬组 hunters may need 20–30% more calories on active hunting days', '工作型猎犬在活跃狩猎日可能需要多20–30%的热量'],
  ['狩猎 season may require 25–40% more calories; reduce intake appropriately in off-season', '狩猎季节可能需要多25–40%的热量；淡季时适当减少摄入'],
  ['白色-coated breeds may benefit from fish-based protein (less likely to stain coat)', '白色被毛犬种可能受益于鱼类蛋白质（较不容易染色被毛）'],
  ['多种 small meals (2–3 per day) prevent hypoglycemia, especially in puppies and small adults', '每天多次小餐（2–3次）预防低血糖，尤其是幼犬和小型成犬'],
  ['多种 small meals daily are often recommended to support GI health', '通常建议每天多次小餐以支持胃肠健康'],
  ['玩具犬组/small-breed formula for appropriate calorie density', '玩具犬/小型犬配方提供适当的热量密度'],
  ['玩具犬组-breed formula designed for their size and caloric needs', '专为其体型和热量需求设计的玩具犬配方'],
  ['玩具犬组-breed kibble sized for the flat face prevents choking and aids digestion', '适合扁平面部大小的玩具犬颗粒狗粮可防止噎食并促进消化'],
  ['否 exercise 1 hour before or 2 hours after meals', '饭前1小时或饭后2小时内禁止运动'],
  ['否 exercise for 1 hour before or 2 hours after eating', '进食前1小时或进食后2小时内禁止运动'],
  ['中型犬 or large-breed formula designed for their size and caloric needs', '中型犬或大型犬配方，专为其体型和热量需求设计'],

  // ── Common English-only diet sentences ────────────────────────────────────
  ['Avoid exercising within an hour of meals — reduces bloat risk significantly', '饭前饭后一小时内避免运动——可显著降低胃扩张风险'],
  ['Maintain lean body weight — excess weight strains joints in a high-mileage dog', '保持苗条体重——超重会使高活动量犬的关节承受额外压力'],
  ['Measure portions carefully — Eskies are prone to weight gain', '仔细量取食物份量——爱斯基摩犬容易增重'],
  ['Puzzle feeders satisfy their sharp minds at mealtime', '益智喂食器在进餐时满足其敏锐的思维需求'],
  ['Active hunting days may require caloric increases of 20–40% above baseline', '活跃狩猎日可能需要在基础热量上增加20–40%'],
  ['Maintain lean body condition — excess weight reduces speed and stresses joints in this running breed', '保持苗条体型——超重会降低速度并使这一奔跑型犬种的关节承压'],
  ['Fresh water must always be available — a hound that has been running all day is significantly dehydrated', '始终保持清洁饮水供应——整天奔跑的猎犬会严重脱水'],
  ['Hairless dogs may need slightly more calories in cold weather for thermoregulation', '无毛犬在寒冷天气中可能需要稍多热量用于体温调节'],
  ['Fish oil supplements reduce skin irritation and allergy symptoms', '鱼油补充剂减少皮肤刺激和过敏症状'],
  ['Avoid grain-free diets unless medically necessary — some are linked to heart issues', '除非医疗需要，否则避免无谷物饮食——部分无谷物食品与心脏问题有关'],
  ['Frozen raw bones provide dental benefits and mental enrichment', '冷冻生骨头有助于牙齿健康和心理丰容'],
  ['Ear cleaning after every swim or water outing prevents infections', '每次游泳或涉水活动后清洁耳道可预防感染'],
  ['Monitor weight carefully in the off-season — they gain weight easily without exercise', '淡季时仔细监控体重——缺乏运动时容易增重'],
  ['Joint supplements from middle age support the long-term soundness of a dog weighing up to 150磅', '中年后开始补充关节营养素，支持体重可达150磅犬只的长期健康'],
  ['Feed twice daily and avoid exercise around mealtimes to reduce the bloat risk common in deep-chested large breeds', '每天两餐，进餐前后避免运动，以降低深胸大型犬常见的胃扩张风险'],
  ['Joint supplements (glucosamine, fish oil) beneficial given the breed\'s size and activity level', '葡萄糖胺、鱼油等关节补充剂有益，考虑到犬种的体型和活动水平'],
  ['Feed twice daily from floor level — avoid raised bowls and restrict exercise around meals to reduce bloat risk', '从地板高度每天两餐喂食——避免使用高脚碗，进餐前后限制运动以降低胃扩张风险'],
  ['Joint supplements from puppyhood benefit this heavy breed\'s developing joints and long-term mobility', '从幼犬期开始补充关节营养素，有益于这一重型犬种发育中的关节和长期活动能力'],
  ['Monitor weight carefully — obesity dramatically worsens breathing, joint, and cardiac issues in this breed', '仔细监控体重——肥胖会大幅加重这一犬种的呼吸、关节和心脏问题'],
  ['Small-breed formula to match body size — 避免过度喂食——多余的体重会给关节带来压力', '小型犬配方匹配体型——避免过度喂食，多余的体重会给关节带来压力'],
  ['Spinal health is critical — weight management reduces IVDD risk dramatically', '脊柱健康至关重要——体重管理可显著降低椎间盘疾病风险'],
  ['Avoid jumping on/off furniture — use ramps or steps to protect the spine', '避免跳上/跳下家具——使用坡道或台阶保护脊柱'],
  ['Quality protein and moderate fat support the ECS\'s active but compact build', '优质蛋白质和适量脂肪支持英国可卡犬活跃但紧凑的体型'],
  ['Split meals into two feedings to avoid bloat and maintain steady energy levels', '分两次喂食以避免胃扩张并保持稳定的能量水平'],
  ['Rest 1 hour before and after meals to prevent GDV', '饭前饭后休息1小时以预防胃扩张扭转'],
  ['Reduce portions significantly in non-hunting/low-exercise periods to prevent obesity', '在非狩猎/低运动量时期显著减少食量以预防肥胖'],
  ['Monitor weight — English Setters can become food-motivated and overeat', '监控体重——英国雪达犬可能因食物驱动而过度进食'],
  ['Use shallow food bowls to accommodate their flat face and prevent eating difficulties', '使用浅碗以适应其扁平的面部并防止进食困难'],
  ['Maintain lean body condition — excess weight significantly increases joint stress in this active breed', '保持苗条体型——超重会显著增加这一活跃犬种的关节压力'],
  ['Feed twice daily rather than once to reduce bloat risk in this deep-chested medium breed', '每天两餐而非一餐，以降低这一深胸中型犬的胃扩张风险'],
  ['Quality protein supports their lean, athletic sporting-dog physique', '优质蛋白质支持其精瘦、运动型猎犬体型'],
  ['Regular ear checks and a diet supporting immune health reduces infection risk', '定期检查耳道，加之支持免疫健康的饮食，可降低感染风险'],
  ['Glucosamine and chondroitin for joint support — both parents are dysplasia risks', '葡萄糖胺和软骨素支持关节健康——双亲犬种均有发育不良风险'],
  ['Two meals per day reduces bloat risk', '每天两餐降低胃扩张风险'],
  ['Real animal protein as the first ingredient — chicken or fish work well for most Frenchies', '真正的动物蛋白质作为首要成分——鸡肉或鱼肉适合大多数法斗'],
  ['Limit fat content — Frenchies gain weight easily, which directly worsens breathing problems', '限制脂肪含量——法斗容易增重，而增重会直接加重呼吸问题'],
  ['Limited-ingredient or grain-free diets can help — French Bulldogs have some of the highest food allergy rates of any breed', '有限配料或无谷物饮食可能有帮助——法国斗牛犬是食物过敏率最高的犬种之一'],
  ['Always use a slow-feed bowl to prevent gulping air, which causes bloating and digestive discomfort', '始终使用慢食碗防止吞入空气，吞气会导致腹胀和消化不适'],
  ['Taurine for cardiac health', '牛磺酸支持心脏健康'],
  ['Joint support supplements', '关节补充剂'],
  ['Probiotics can help manage their famously sensitive digestive systems', '益生菌有助于管理其出了名的敏感消化系统'],
  ['Joint supplements benefit any large working dog that will spend years on demanding terrain', '关节补充剂有益于任何将在恶劣地形上工作多年的大型工作犬'],
  ['Feed twice daily and limit exercise 30–60 minutes before and after meals to reduce bloat risk', '每天两餐，进餐前后30–60分钟限制运动以降低胃扩张风险'],
  ['Feed twice daily from a raised bowl and restrict exercise for 1 hour before and after eating to reduce GDV risk', '用高脚碗每天两餐喂食，进食前后1小时限制运动以降低GDV风险'],
  ['Monitor weight carefully — an obese 超大型犬 Schnauzer puts enormous strain on joints and cardiovascular system', '仔细监控体重——超重的巨型雪纳瑞会对关节和心血管系统造成巨大压力'],
  ['Monitor weight — their low-set body can carry excess weight invisibly until it becomes problematic', '监控体重——其低矮的身体可能在超重变成问题前隐藏额外重量'],
  ['Avoid free-feeding — measure portions to maintain lean weight', '避免自由取食——量取份量以保持苗条体重'],
  ['Measured meals — both parent breeds are notorious food-motivated overeaters', '量取份量喂食——两个亲本犬种都是出了名的贪吃'],
  ['Glucosamine and chondroitin from age 5 onward for joint support', '5岁后开始补充葡萄糖胺和软骨素以支持关节健康'],
  ['Limit treats to 10% of daily calories to prevent obesity', '将零食限制在每日热量的10%以内，预防肥胖'],
  ['Real animal protein (chicken or salmon) as the first ingredient', '真正的动物蛋白质（鸡肉或三文鱼）作为首要成分'],
  ['Portion control is critical — Goldens are extremely food-motivated and prone to obesity', '份量控制至关重要——金毛寻回犬极度贪吃且易于肥胖'],
  ['Active hunting dogs need significantly more calories on working days', '活跃的狩猎犬在工作日需要显著更多的热量'],
  ['Quality protein supports their active, pack-hunting physique', '优质蛋白质支持其活跃的群体狩猎体型'],
  ['Hounds tend to gorge — measure meals and don\'t free-feed', '猎犬容易暴食——量取份量，避免自由取食'],
  ['Joint support supplements useful for this energetic, low-slung breed', '关节补充剂对这一精力旺盛、矮腿犬种有益'],
  ['大型犬-breed or giant-breed puppy formula ONLY for the first 18–24 months — standard puppy food causes too-rapid growth and dramatically increases joint problems', '前18–24个月只使用大型犬或巨型犬幼犬配方——标准幼犬粮会导致过快生长并大幅增加关节问题'],
  ['Controlled protein and calcium levels during puppyhood — Great Danes grow so fast that excess nutrition causes skeletal deformities', '幼犬期控制蛋白质和钙的摄入——大丹犬生长如此迅速，过多营养会导致骨骼畸形'],
  ['NEVER feed one large meal — always split into 2–3 portions. Bloat (GDV) is the #1 killer of Great Danes and eating patterns directly affect risk', '绝对不要一次喂一大餐——始终分成2–3份。胃扩张（GDV）是大丹犬的头号杀手，饮食方式直接影响风险'],
  ['Elevated feeding bowls were once recommended but are now controversial — ask your vet about the latest guidance on bloat prevention', '高脚喂食碗曾被推荐，但现在存在争议——请咨询兽医关于预防胃扩张的最新指导'],
  ['Joint supplements (glucosamine, chondroitin, fish oil) from puppyhood — their immense size puts extraordinary stress on developing joints', '从幼犬期开始补充关节营养素（葡萄糖胺、软骨素、鱼油）——其庞大体型对发育中的关节造成巨大压力'],
  ['Split meals into two servings and avoid strenuous exercise before and after eating to reduce GDV risk substantially', '将食物分成两份喂食，进食前后避免剧烈运动，可大幅降低GDV风险'],
  ['Joint supplements (glucosamine, chondroitin) are beneficial starting from middle age in this large working breed', '在这一大型工作犬种中，从中年开始补充关节营养素（葡萄糖胺、软骨素）有益'],
  ['Feed twice daily, never once — reduces bloat risk significantly', '每天两餐，绝不一次喂食——可显著降低胃扩张风险'],
  ['Calcium and phosphorus balance is critical during the long growth phase', '漫长生长期中钙磷平衡至关重要'],
  ['Lean, high-quality protein for greyhound physique', '精瘦高质量蛋白质适合灵缇体型'],
  ['Calcium for bone density', '钙质支持骨密度'],
  ['Active hunting days call for 20–30% more calories than the baseline', '活跃狩猎日比基础摄入需要多20–30%的热量'],
  ['Food motivation makes Harriers highly treat-responsive — great for training, risky for weight gain', '食物驱动使哈利犬对零食极为敏感——有利于训练，但有增重风险'],
  ['Puzzle feeders slow eating and provide mental stimulation for this scent-obsessed breed', '益智喂食器减缓进食速度，为这一嗅觉痴迷的犬种提供心理刺激'],
  ['Probiotic supplement — Poodle parent is prone to sensitive digestion', '益生菌补充剂——贵宾犬亲本易有敏感消化'],
  ['Two measured meals daily to prevent obesity from overfeeding', '每天两次量取份量喂食，防止过度喂食导致肥胖'],
  ['Consistent meal schedule — Huskies can be picky eaters and may skip meals', '规律的饮食时间表——哈士奇可能挑食并跳过某餐'],
  ['Feed two meals per day to reduce bloat risk for this deep-chested breed', '每天两餐以降低这一深胸犬种的胃扩张风险'],
  ['Inform your vet of sighthound anesthesia sensitivity before any procedures', '任何手术前告知兽医视觉猎犬的麻醉敏感性'],
  ['Feed consistent meals at regular times to support their energetic herding lifestyle', '在固定时间规律喂食，支持其充满活力的牧羊生活方式'],
  ['B vitamins for energy metabolism', 'B族维生素支持能量代谢'],
  ['Split meals reduce bloat risk — never feed one large daily meal', '分餐喂食降低胃扩张风险——绝不每天一次性大量喂食'],
  ['Avoid exercise for at least an hour after eating', '进食后至少一小时内避免运动'],
  ['Some Irish Setters have grain sensitivities — consult your vet if skin or digestive issues arise', '部分爱尔兰雪达犬对谷物敏感——如出现皮肤或消化问题请咨询兽医'],
  ['Zinc for foot/pad health', '锌支持爪垫健康'],
  ['Antioxidants for immune support', '抗氧化剂支持免疫系统'],
  ['Glucosamine supplements from middle age support joint health', '中年后补充葡萄糖胺支持关节健康'],
  ['Feed two meals daily — this deep-chested breed has some bloat susceptibility', '每天两餐——这一深胸犬种有一定胃扩张易感性'],
  ['Feed from floor level, not raised bowls — research suggests raised bowls may increase bloat risk in giant breeds', '从地板高度喂食，而非高脚碗——研究表明高脚碗可能增加巨型犬的胃扩张风险'],
  ['Split food into 2–3 meals and restrict exercise before and after eating to reduce GDV risk substantially', '将食物分成2–3份，进食前后限制运动，可大幅降低GDV风险'],
  ['Cardiac support supplements (fish oil, CoQ10) are worth discussing with your vet given the breed\'s DCM risk', '考虑到犬种的扩张型心肌病风险，值得与兽医讨论心脏支持补充剂（鱼油、辅酶Q10）'],
  ['Dental health is critical — hard kibble or dental chews help', '牙齿健康至关重要——硬粒狗粮或洁齿零食有帮助'],
  ['Calcium and phosphorus balance supports their fragile bone structure', '钙磷平衡支持其脆弱的骨骼结构'],
  ['Avoid obesity — extra weight stresses the fine legs', '避免肥胖——额外体重会给纤细的腿部造成压力'],
  ['Warm meals in cold weather help these temperature-sensitive dogs', '寒冷天气中温热食物有助于这些对温度敏感的犬只'],
  ['Fresh water is essential — brachycephalic breeds dehydrate more easily than normal-nosed dogs', '充足饮水至关重要——短头犬种比正常鼻型犬更容易脱水'],
  ['Cardiac-supporting diets (taurine, L-carnitine) may be beneficial as the breed ages', '随着犬种年龄增长，支持心脏健康的饮食（牛磺酸、L-肉碱）可能有益'],
  ['Quality protein keeps the muscular spitz body in shape', '优质蛋白质保持尖嘴犬强健体型'],
  ['Avoid grain-free diets unless medically necessary', '除非医疗必要，否则避免无谷物饮食'],
  ['Calcium balance matters for their dense bone structure', '钙平衡对其致密骨骼结构很重要'],
  ['Zinc for skin health', '锌支持皮肤健康'],
  ['Joint support critical for giant breed', '关节支持对巨型犬种至关重要'],
  ['Antioxidants for immune function', '抗氧化剂支持免疫功能'],
  ['Feed two meals daily to reduce bloat risk — this deep-chested breed is susceptible to GDV', '每天两餐降低胃扩张风险——这一深胸犬种易患GDV'],
  ['Avoid exercise for one hour before and after feeding to further reduce bloat risk', '进食前后一小时内避免运动，进一步降低胃扩张风险'],
  ['Foods with glucosamine & chondroitin — helps their joints as they age', '含葡萄糖胺和软骨素的食物——随着年龄增长有助于关节健康'],
  ['大型犬-breed formulas — designed for their size and growth rate', '大型犬配方——专为其体型和生长速度设计'],
  ['Avoid: artificial colors, BHA/BHT preservatives, excessive fillers', '避免：人工色素、BHA/BHT防腐剂、过多填充物'],
  ['Commercial treats designed for large breeds', '专为大型犬设计的商业零食'],
  ['Portion control — Labs love to eat and will overeat if allowed', '份量控制——拉布拉多犬爱吃，如不加控制会过度进食'],
  ['Glucosamine supplement from age 5+ for joint health', '5岁后补充葡萄糖胺以支持关节健康'],
  ['Feed twice daily at consistent times to support stable energy for work', '在固定时间每天两餐喂食，支持工作所需的稳定能量'],
  ['Joint support for mountain-bred dog', '关节支持适合山地犬种'],
  ['Monitor weight carefully — the breed can gain weight easily, which stresses the long back and short legs', '仔细监控体重——该犬种容易增重，而增重会给长背和短腿造成压力'],
  ['Feed 2–3 small meals daily — never one large meal — to reduce bloat risk', '每天2–3次小份喂食——绝不一次性大量喂食——以降低胃扩张风险'],
  ['Tear-stain management diet — some foods contribute to staining around white fur', '泪痕管理饮食——某些食物会加重白色毛发周围的泪痕'],
  ['Dental health kibble or regular tooth brushing is essential', '牙齿健康狗粮或定期刷牙至关重要'],
  ['The short, smooth coat is low-maintenance but benefits from omega-3 supplementation for skin health', '短而光滑的被毛易于维护，但补充omega-3可改善皮肤健康'],
  ['小型犬 breed formula recommended for 玩具犬组 variety; standard small breed formula suits Standard variety', '玩具型推荐小型犬配方；标准型使用标准小型犬配方'],
  ['Feed giant breed puppy formula — do NOT use adult food for puppies as calcium/phosphorus ratios matter greatly', '使用巨型犬幼犬配方——切勿给幼犬喂食成犬粮，因为钙磷比例非常重要'],
  ['Never exercise your Mastiff for at least 1 hour before or after feeding to reduce bloat risk', '进食前后至少1小时内不要让獒犬运动，以降低胃扩张风险'],
  ['Elevated food bowls were once recommended but studies now suggest they may actually increase bloat risk — consult your vet', '高脚碗曾被推荐，但研究现在表明可能实际上增加胃扩张风险——请咨询兽医'],
  ['Glucosamine and chondroitin supplements support joint health in this heavy breed', '葡萄糖胺和软骨素补充剂支持这一重型犬种的关节健康'],
  ['Be aware of MDR1 mutation — some drugs/dewormers are dangerous; always inform your vet', '注意MDR1基因突变——某些药物/驱虫药可能危险；始终告知兽医'],
  ['Avoid free-feeding — Mini Bull Terriers will overeat enthusiastically if allowed', '避免自由取食——迷你斗牛梗如不加控制会热情地过度进食'],
  ['Feed measured meals twice daily to maintain healthy weight', '每天两次量取份量喂食以保持健康体重'],
  ['Tiny-breed or toy formula kibble — smaller kibble size prevents choking', '迷你犬或玩具犬配方颗粒——较小的颗粒大小可防止噎食'],
  ['Avoid table scraps — tiny dogs gain weight fast', '避免喂食桌上剩食——小型犬增重很快'],
  ['Active Mudis competing in dog sports may need 20–30% more calories during intensive training', '参加犬类运动竞赛的活跃普米犬在强化训练期间可能需要多20–30%的热量'],
  ['Monitor weight — a lean body condition is essential for this breed\'s agility performance', '监控体重——精瘦体型对这一犬种的敏捷表现至关重要'],
  ['Feed twice daily from floor level; avoid raised bowls and exercise around mealtimes to reduce bloat risk', '在地板高度每天两餐喂食；避免使用高脚碗和在进餐时间前后运动，以降低胃扩张风险'],
  ['Keep paper towels or dedicated Neo rags in every room — the Neo drools constantly and substantially', '在每个房间准备纸巾或专用毛巾——那不勒斯獒犬持续大量流口水'],
  ['Skin-supporting supplements (fish oil, vitamin E) help maintain the health of the extensive skin fold surface area', '皮肤支持补充剂（鱼油、维生素E）有助于维护大量皮肤褶皱表面的健康'],
  ['Support joint health with appropriate supplements if very active', '如果非常活跃，使用适当补充剂支持关节健康'],
  ['Fiber for digestive health', '膳食纤维支持消化健康'],
  ['Elkhounds are notorious for weight gain — measure meals precisely and limit treats', '挪威猎麋犬以容易增重而闻名——精确量取食物份量并限制零食'],
  ['Joint supplements beneficial for older dogs given their athletic workload history', '考虑到其运动工作历史，关节补充剂对老年犬有益'],
  ['Many Lundehunds require a specialized low-fat, highly digestible diet — consult your vet', '许多挪威隆德猎犬需要专业的低脂、高消化率饮食——请咨询兽医'],
  ['Monitor weight carefully — GI issues can cause sudden weight loss', '仔细监控体重——胃肠问题可能导致突然体重下降'],
  ['Vitamin B12 supplementation is often required for affected individuals', '受影响的个体通常需要补充维生素B12'],
  ['High-quality protein fuels the Toller\'s intense athleticism and retriever working drive', '优质蛋白质为托勒犬出色的运动能力和寻回工作动力提供能量'],
  ['Fish-based diets are particularly well-suited to this Canadian water dog\'s ancestral nutrition', '基于鱼类的饮食特别适合这一加拿大水犬的传统营养需求'],
  ['Feed twice daily; split meals help sustain energy levels throughout a Toller\'s high-activity day', '每天两餐；分餐有助于维持托勒犬高活动量日全天的能量水平'],
  ['Two meals daily — never one large meal for this bloat-susceptible deep-chested breed', '每天两餐——绝不一次性大量喂食这一易患胃扩张的深胸犬种'],
  ['Elevated feeders are sometimes recommended for large breeds to reduce bloat risk — consult your vet', '高脚喂食器有时被推荐用于大型犬以降低胃扩张风险——请咨询兽医'],
  ['Monitor weight carefully; the dense 蓬乱 coat can mask gradual weight gain', '仔细监控体重；蓬乱的浓密被毛可能掩盖逐渐增加的体重'],
  ['Choose small-breed kibble to support dental health', '选择小型犬颗粒狗粮以支持牙齿健康'],
  ['Fresh water always available — Papillons can be prone to urinary issues', '始终提供清洁饮水——蝴蝶犬可能易患泌尿问题'],
  ['Limit treats to 10% of daily calories', '将零食限制在每日热量的10%以内'],
  ['高 animal protein for muscle maintenance', '高动物蛋白质用于肌肉维护'],
  ['适中 fat for sustained energy', '适量脂肪提供持续能量'],
  ['Very small breed with minimal caloric needs — overfeeding is the 最常见 Pekingese health mistake', '热量需求极低的极小型犬——过度喂食是北京犬最常见的健康错误'],
  ['Choose small-breed kibble sized for flat-faced breeds to reduce swallowing difficulty and choking risk', '选择专为扁脸犬种设计大小的小型犬颗粒狗粮，减少吞咽困难和噎食风险'],
  ['Dental care is essential — the flat face creates crowded teeth prone to disease; brush teeth several times weekly', '牙齿护理至关重要——扁平脸部造成牙齿拥挤易患疾病；每周刷牙数次'],
  ['Avoid exercise in heat; the Peke\'s flat face makes thermoregulation difficult and heatstroke a serious risk', '避免在炎热天气运动；北京犬的扁平脸部使体温调节困难，中暑是严重风险'],
  ['Keep PBGVs lean — excess weight strains the long, low spine', '保持小格里芬旺代巴吉度犬苗条——超重会给其长而低矮的脊柱造成压力'],
  ['Regular ear cleaning reduces infection risk from food and moisture', '定期清洁耳道降低因食物和潮湿引起的感染风险'],
  ['Feed two meals per day to reduce bloat risk in this deep-chested breed', '每天两餐以降低这一深胸犬种的胃扩张风险'],
  ['Always feed two meals daily — never one large meal for this bloat-prone breed', '始终每天两餐——绝不一次性大量喂食这一易患胃扩张的犬种'],
  ['Avoid vigorous exercise for an hour before and after meals', '饭前饭后一小时内避免剧烈运动'],
  ['Active working Pointers in hunting season may require 25–50% more calories than sedentary pets', '狩猎季节活跃工作的指示犬可能需要比安静宠物多25–50%的热量'],
  ['Feed 30–60 minutes after exercise — never immediately before or after vigorous activity to prevent bloat', '运动后30–60分钟喂食——绝不在剧烈运动前后立即喂食以预防胃扩张'],
  ['Maintain a lean body condition — overweight Pointers have reduced athletic performance and joint health', '保持精瘦体型——超重的指示犬运动表现和关节健康均会下降'],
  ['Antioxidants for eye health (PRA risk)', '抗氧化剂支持眼睛健康（进行性视网膜萎缩风险）'],
  ['Digestible, high-quality carbohydrates — Poodles are prone to Addison\'s disease, and consistent, high-quality nutrition supports adrenal health', '易消化的高质量碳水化合物——贵宾犬易患艾迪生病，一致的高质量营养有助于肾上腺健康'],
  ['Avoid high-fat diets — Standard Poodles are susceptible to bloat (GDV), and rich foods increase this risk', '避免高脂肪饮食——标准贵宾犬易患胃扩张（GDV），丰盛食物会增加此风险'],
  ['Feed before swimming sessions, not right after vigorous activity', '在游泳前喂食，而非剧烈活动后立即喂食'],
  ['Strict portion control is essential — Pugs are extremely food-motivated and gain weight easily', '严格的份量控制至关重要——巴哥犬极度贪吃且容易增重'],
  ['Avoid exercise immediately after eating to reduce aspiration risk given their airway anatomy', '进食后立即避免运动，减少因其气道解剖结构带来的吸入风险'],
  ['Choose foods with moderate fat content; obesity dramatically worsens BOAS breathing issues', '选择适量脂肪含量的食物；肥胖会大幅加重BOAS呼吸问题'],
  ['Feed from a raised bowl to ease swallowing, and select kibble sized for flat-faced breeds', '从高脚碗喂食以便吞咽，选择适合扁脸犬种大小的颗粒狗粮'],
  ['Never free-feed — Puggles will eat until sick', '绝不自由取食——巴哥比格混血会一直吃到生病'],
  ['Slow feeders help prevent gulping, which can cause digestive issues', '慢食碗有助于防止狼吞虎咽，吞咽过快可能导致消化问题'],
  ['Dry food is preferred — wet food and cords don\'t mix well', '首选干粮——湿粮和绳状被毛不相适'],
  ['Puzzle feeders satisfy the Pumi\'s need for mental stimulation even at mealtimes', '益智喂食器即使在进餐时也能满足普米犬的心理刺激需求'],
  ['Despite their small size, active Pyr Sheps may need more calories than expected', '尽管体型小，活跃的比利牛斯牧羊犬可能需要比预期更多的热量'],
  ['Monitor weight carefully during high-activity periods — they can lose condition quickly when working hard', '高活动量期间仔细监控体重——努力工作时它们可能迅速失去体型'],
  ['Monitor weight — Redbones can put on weight quickly if exercise decreases', '监控体重——如果运动量减少，红骨猎浣熊犬可能迅速增重'],
  ['Never exercise immediately before or after meals — reduces bloat risk', '饭前饭后立即禁止运动——降低胃扩张风险'],
  ['Monitor weight — an overweight Ridgeback puts stress on joints', '监控体重——超重的罗得西亚脊背犬会给关节造成压力'],
  ['Two meals daily, never exercise within 1 hour of eating — bloat prevention is critical', '每天两餐，进食后1小时内禁止运动——预防胃扩张至关重要'],
  ['Glucosamine and chondroitin from age 3 onward for large joint support', '3岁后补充葡萄糖胺和软骨素以支持大型关节健康'],
  ['Protein-rich diet to maintain muscle mass — powerful dogs need sustained protein', '富含蛋白质的饮食维持肌肉质量——强壮的犬只需要持续的蛋白质摄入'],
  ['大型犬-breed formula for puppies — Rottweilers grow quickly and need controlled calcium-to-phosphorus ratios to protect developing joints', '大型犬幼犬配方——罗威纳犬生长迅速，需要控制钙磷比例以保护发育中的关节'],
  ['Glucosamine and chondroitin supplements — Rotties are prone to hip and elbow dysplasia, and joint support should start early', '葡萄糖胺和软骨素补充剂——罗威纳犬易患髋关节和肘关节发育不良，应早期开始关节支持'],
  ['Never feed one large meal — always split into 2 portions to significantly reduce the risk of life-threatening bloat (GDV)', '绝不一次性大量喂食——始终分成2份以显著降低威胁生命的胃扩张（GDV）风险'],
  ['Avoid high-fat foods and table scraps — Rottweilers can develop pancreatitis, and excess weight worsens joint problems', '避免高脂肪食物和桌上剩食——罗威纳犬可能患胰腺炎，超重会加重关节问题'],
  ['Avoid obesity — carries excess weight surprisingly easily despite high energy; measure meals precisely', '避免肥胖——尽管精力充沛，但容易意外增重；精确量取食物份量'],
  ['Dental chews help prevent tartar buildup, a common issue in small terriers with close-set teeth', '洁齿零食有助于防止牙垢积累，这是牙齿紧密的小型梗犬的常见问题'],
  ['Feed twice daily; small stomachs mean one large meal can cause digestive upset', '每天两餐；小胃容量意味着一次性大餐可能导致消化不适'],
  ['Calcium for fragile bones', '钙质支持脆弱骨骼'],
  ['Complex carbohydrates to prevent hypoglycemia', '复杂碳水化合物预防低血糖'],
  ['Two elevated meals daily (never exercise within 1 hour) to reduce bloat risk', '每天两次高脚碗喂食（1小时内禁止运动）以降低胃扩张风险'],
  ['Glucosamine and chondroitin from year 2 onward for massive joint support', '第2年后补充葡萄糖胺和软骨素以支持巨大关节健康'],
  ['Calorie-dense food — giant dogs burn more calories simply existing', '高热量密度食物——巨型犬仅仅维持生存就消耗更多热量'],
  ['Always use giant/large breed puppy formula — regular puppy food can cause dangerous overgrowth', '始终使用巨型/大型犬幼犬配方——普通幼犬粮可能导致危险的过度生长'],
  ['Never feed one large meal per day — split into 2–3 meals to reduce bloat risk', '绝不每天只喂一次大餐——分成2–3餐以降低胃扩张风险'],
  ['Glucosamine and chondroitin supplements support joint health under the heavy frame', '葡萄糖胺和软骨素补充剂在沉重体型下支持关节健康'],
  ['Watch weight carefully — even a few extra pounds is significant stress on giant breed joints', '仔细监控体重——即使多几磅对巨型犬关节也是显著的压力'],
  ['Lean protein for greyhound-type physique', '精瘦蛋白质适合灵缇型体型'],
  ['Antioxidants for longevity', '抗氧化剂支持长寿'],
  ['Monitor weight carefully — this breed can gain weight despite high energy levels', '仔细监控体重——这一犬种尽管精力旺盛也可能增重'],
  ['Puzzle feeders and slow bowls suit this mentally active breed\'s need for stimulation at mealtimes', '益智喂食器和慢食碗满足这一思维活跃犬种在进餐时对刺激的需求'],
  ['Lean protein for maintaining giant sighthound physique', '精瘦蛋白质用于维持巨型视觉猎犬体型'],
  ['Calcium carefully managed during growth', '生长期谨慎管理钙的摄入'],
  ['Monitor treat intake — a charismatic Sealyham will absolutely negotiate for more food', '监控零食摄入——迷人的西利汉梗绝对会讨要更多食物'],
  ['Fish oil supplements keep their thick coat healthy and reduce matting', '鱼油补充剂保持其浓密被毛健康并减少打结'],
  ['Feed twice daily — reduces bloat risk for large dogs', '每天两餐——降低大型犬的胃扩张风险'],
  ['Probiotic supplements may help with digestive sensitivity common in the breed', '益生菌补充剂可能有助于该犬种常见的消化敏感性'],
  ['Grain-free or limited-ingredient formulas may help if allergies are suspected', '如果怀疑过敏，无谷物或有限配料配方可能有帮助'],
  ['Measure meals precisely — Shibas are not typically prone to bloat but obesity shortens their lives', '精确量取食物份量——柴犬通常不易患胃扩张，但肥胖会缩短其寿命'],
  ['Dental-health focused treats and foods — Shih Tzus are prone to dental disease due to their small mouths and crowded teeth', '专注牙齿健康的零食和食物——西施犬因小嘴和拥挤的牙齿而易患牙科疾病'],
  ['Avoid foods with artificial dyes — the Shih Tzu\'s white facial hair is very susceptible to staining from dyes and low-quality ingredients', '避免含人工染料的食物——西施犬的白色面部毛发非常容易被染料和低质量配料染色'],
  ['Higher fat content than most breeds — Huskies were bred to metabolize fat efficiently for sustained endurance over long distances', '比大多数犬种更高的脂肪含量——哈士奇被培育为高效代谢脂肪以维持长距离持续耐力'],
  ['Zinc supplementation may be needed — Huskies are prone to zinc-responsive dermatosis, a skin condition caused by zinc deficiency', '可能需要补充锌——哈士奇易患锌反应性皮肤病，这是由锌缺乏引起的皮肤状况'],
  ['Do NOT overfeed — Huskies naturally self-regulate and can maintain a healthy weight on surprisingly small amounts of food compared to dogs their size', '不要过度喂食——哈士奇天然自我调节，与同体型犬相比，进食量出人意料地少就能维持健康体重'],
  ['Monitor for signs of diabetes — excessive thirst or urination warrants a vet visit', '监测糖尿病迹象——过度口渴或排尿需要就医'],
  ['Lean, high-quality protein supports muscle without promoting excess weight on the long spine', '精瘦高质量蛋白质支持肌肉而不在长脊椎上促进超重'],
  ['Calcium and phosphorus balance is critical during puppyhood to prevent the breed\'s growth plate issues', '幼犬期钙磷平衡至关重要，以防止该犬种的生长板问题'],
  ['Monitor weight closely — the long coat can hide gradual weight gain', '密切监控体重——长毛可能掩盖逐渐增加的体重'],
  ['Feed two small meals to reduce bloat risk — never one large meal for a deep-chested breed', '每天两次小份喂食以降低胃扩张风险——对深胸犬种绝不一次性大量喂食'],
  ['Treats should not exceed 10% of daily caloric intake for this food-motivated breed', '对于这一食物驱动的犬种，零食不应超过每日热量摄入的10%'],
  ['Digestive enzymes (EPI risk)', '消化酶（胰腺外分泌功能不全风险）'],
  ['The beard and mustache trap food and water — clean after meals to prevent odor and skin irritation', '胡须和髭须会沾染食物和水——进餐后清洁以防止异味和皮肤刺激'],
  ['Feed twice daily; a hunting dog in active season may need 20–30% more calories than during off-season rest', '每天两餐；活跃狩猎季节的猎犬可能比淡季休息时需要多20–30%的热量'],
  ['Active medium-breed formula with high protein content', '高蛋白质活跃中型犬配方'],
  ['Regular ear cleaning paired with diet — prone to ear infections', '定期耳道清洁配合饮食——易患耳道感染'],
  ['Two meals daily on a consistent schedule for digestive health', '每天两餐按固定时间喂食以促进消化健康'],
  ['Joint supplements become beneficial from middle age given the breed\'s compact, muscular build', '考虑到该犬种紧凑、肌肉发达的体型，从中年开始补充关节营养素有益'],
  ['Dental health is important — short snouts can lead to crowded teeth; dental chews and brushing help', '牙齿健康重要——短吻部可能导致牙齿拥挤；洁齿零食和刷牙有帮助'],
  ['The beard and mustache should be rinsed after meals to prevent staining and odor', '进餐后冲洗胡须和髭须以防止染色和异味'],
  ['Joint supplements (glucosamine/chondroitin) may benefit the heavy-bodied, short-legged structure', '关节补充剂（葡萄糖胺/软骨素）可能有益于身体重、腿短的体型'],
  ['Elevated feeding bowls can help prevent bloating in the barrel-chested body', '高脚喂食碗有助于防止桶形胸体型的腹胀'],
  ['Monitor weight carefully — excess weight on the long back can cause spinal stress', '仔细监控体重——长背上的超重可能导致脊柱压力'],
  ['大型犬/giant-breed formula slows growth rate, protecting joints during development', '大型犬/巨型犬配方减缓生长速度，保护发育期关节'],
  ['Tibetan Mastiffs often self-regulate — some eat far less than expected for their size', '藏獒通常自我调节——有些进食量远低于其体型预期'],
  ['Avoid calcium supplementation in puppies — disrupts giant-breed bone development', '避免给幼犬补充钙质——会干扰巨型犬的骨骼发育'],
  ['Quality protein supports the Tibetan 梗犬组\'s moderate activity level and longevity', '优质蛋白质支持藏梗适度的活动水平和长寿'],
  ['The dense coat benefits from omega-3 fatty acids that maintain coat condition and skin health', '浓密的被毛得益于维持被毛状态和皮肤健康的omega-3脂肪酸'],
  ['Feed twice daily; the Tibetan 梗犬组\'s hardy Himalayan ancestry means it is not typically finicky but benefits from consistency', '每天两餐；藏梗强健的喜马拉雅血统意味着它通常不挑食，但受益于规律性'],
  ['高-quality small-breed dry kibble supports dental health', '优质小型犬干粮支持牙齿健康'],
  ['3 small meals daily for puppies to prevent hypoglycemia', '幼犬每天3次小份喂食以预防低血糖'],
  ['Regular ear cleaning should complement feeding routine to prevent infections', '定期耳道清洁应作为日常喂食的补充，以预防感染'],
  ['Monitor weight — Welshies can gain weight easily if under-exercised', '监控体重——威尔士梗如运动不足容易增重'],
  ['Ear care paired with diet: avoid foods that may trigger skin/ear allergies', '耳道护理配合饮食：避免可能触发皮肤/耳道过敏的食物'],
  ['Feed twice daily on a schedule — regular mealtimes help manage energy levels in this active terrier', '按时每天两餐喂食——固定进餐时间有助于管理这一活跃梗犬的能量水平'],
  ['Choose formulas with a single, high-quality protein source to help identify food sensitivities', '选择含单一优质蛋白质来源的配方，有助于识别食物敏感性'],
  ['Avoid artificial dyes and preservatives which may aggravate allergies', '避免可能加重过敏的人工染料和防腐剂'],
  ['Limited-ingredient diets can help manage food allergy symptoms', '有限配料饮食有助于管理食物过敏症状'],
  ['Monitor weight closely — Westies can become overweight which stresses small joints', '密切监控体重——西高地白梗可能超重，给小型关节造成压力'],
  ['Limited-ingredient diet if skin sensitivity develops (Westie trait)', '如果出现皮肤敏感（西高地白梗特征），使用有限配料饮食'],
  ['Avoid foods with corn, soy, or wheat if skin issues appear', '如出现皮肤问题，避免含玉米、大豆或小麦的食物'],
  ['Dental health diet — terrier-mix teeth need regular attention', '牙齿健康饮食——梗犬混血的牙齿需要定期关注'],
  ['Sensitive stomachs are common — gradual food transitions if changing brands', '敏感胃部很常见——更换品牌时逐渐过渡'],
  ['Active Whippets competing in lure coursing or racing may need higher caloric intake', '参加机械兔赛跑或竞速的活跃惠比特犬可能需要更高的热量摄入'],
  ['Dental chews support oral health in this long-lived breed', '洁齿零食支持这一长寿犬种的口腔健康'],
  ['Glucosamine and chondroitin for joint support from age 5+', '5岁后补充葡萄糖胺和软骨素支持关节健康'],
  ['Feed before long hunts — they need fuel, not an empty stomach', '长时间狩猎前喂食——它们需要能量，不能空腹'],
  ['Healthy fats for sustained energy', '健康脂肪提供持续能量'],
  ['Glucosamine and chondroitin for joints', '葡萄糖胺和软骨素支持关节健康'],
  ['Vitamin E supports skin barrier — look for it in quality pet foods', '维生素E支持皮肤屏障——在优质宠物食品中寻找此成分'],
  ['Do NOT brush the curly coat — it destroys curl structure; minimal grooming is best', '绝不梳理卷毛——会破坏卷毛结构；最少的美容是最好的'],
  ['Monitor weight as Curlies can gain weight when under-exercised during off-season', '监控体重，因为卷毛寻回犬在淡季运动不足时可能增重'],
  ['Real meat protein as the first ingredient — avoid fillers that pack on unnecessary calories', '以真实肉类蛋白质为首要成分——避免增加不必要热量的填充物'],
  ['Chondroitin and glucosamine supplements support spinal and joint health in a breed prone to IVDD', '软骨素和葡萄糖胺补充剂支持易患椎间盘疾病犬种的脊柱和关节健康'],
  ['Maintain lean weight strictly — even modest excess weight significantly increases spinal injury risk', '严格保持精瘦体重——即使适度超重也会显著增加脊柱受伤风险'],
  ['Glucosamine and chondroitin supplementation supports spinal and joint health', '葡萄糖胺和软骨素补充剂支持脊柱和关节健康'],
  ['The mixed hard-and-soft coat benefits from omega fatty acid supplementation', '软硬混合被毛受益于omega脂肪酸补充'],
  ['Dental health diet to manage crowding risk', '牙齿健康饮食管理牙齿拥挤风险'],
  ['Real meat as the first ingredient — Beagles do well on chicken, turkey, or fish-based formulas', '以真实肉类为首要成分——比格犬在鸡肉、火鸡肉或鱼肉配方上表现良好'],
  ['Measured portions at every single meal — Beagles have no "off switch" and will eat until sick', '每顿饭量取份量——比格犬没有"停止"键，会一直吃到生病'],
  ['Avoid free-feeding at all costs — always put food down for 15 minutes then remove it', '不惜一切代价避免自由取食——始终将食物放下15分钟后取走'],
  ['Avoid: artificial colors, BHA/BHT preservatives, and corn or soy as the primary ingredient', '避免：人工色素、BHA/BHT防腐剂，以及以玉米或大豆为主要成分'],
  ['Taurine and L-carnitine for cardiac support', '牛磺酸和L-肉碱支持心脏健康'],
  ['Glucosamine for joint integrity', '葡萄糖胺维护关节完整性'],
  ['Feed twice daily; high-energy herding dogs benefit from consistent meal scheduling to regulate energy levels', '每天两餐；高能量牧羊犬受益于一致的喂食时间表以调节能量水平'],
  ['Monitor weight closely in retired working dogs — the transition to lower activity requires an immediate caloric adjustment', '密切监控退休工作犬的体重——向较低活动量的过渡需要立即调整热量'],
  ['Highly digestible protein sources (chicken, turkey, fish) minimize GI sensitivity in this breed', '高消化率蛋白质来源（鸡肉、火鸡肉、鱼肉）最大程度减少该犬种的胃肠敏感性'],
  ['Avoid foods with artificial additives, fillers, and low-quality ingredients that trigger digestive upset', '避免含有人工添加剂、填充物和触发消化不适的低质量成分的食物'],
  ['Always feed two meals daily — never one large meal for this bloat-prone breed', '始终每天两餐——绝不一次性大量喂食这一易患胃扩张的犬种'],
  ['Avoid exercise for 60–90 minutes before and after meals', '饭前饭后60–90分钟内避免运动'],
  ['Never use raised food bowls — contrary to old advice, they may increase bloat risk', '不要使用高脚碗——与旧建议相反，它们可能增加胃扩张风险'],
  ['Avoid exercise within 1 hour before or after meals — bloat prevention is critical', '饭前后1小时内避免运动——预防胃扩张至关重要'],
  ['Fresh water always available — Bloodhounds drink heavily, especially after tracking', '始终提供充足饮水——寻血猎犬大量饮水，尤其在追踪后'],
  ['Feed two smaller meals rather than one large meal to reduce bloat risk', '每天两次较小份量喂食，而非一次大量喂食，以降低胃扩张风险'],
  ['Avoid exercise for 1 hour before and after meals — critical for deep-chested breeds', '饭前后1小时内避免运动——对深胸犬种至关重要'],
  ['Feed twice daily from floor level; restrict exercise 1 hour before and after meals to reduce GDV risk', '在地板高度每天两餐喂食；饭前后1小时限制运动以降低GDV风险'],
  ['Joint supplements from puppyhood are particularly important for this extraordinarily heavy breed', '对于这一体重极大的犬种，从幼犬期开始补充关节营养素尤为重要'],
  ['Monitor weight rigorously — an obese 200-lb dog faces dramatically amplified health consequences', '严格监控体重——200磅的肥胖犬只面临大幅放大的健康后果'],
  ['Avoid grain-containing foods if CECS is diagnosed — some cases respond to gluten-free diets', '如诊断出CECS，避免含谷物食物——部分病例对无麸质饮食有反应'],
  ['Dental care is important for small terriers prone to tartar buildup; dental chews and brushing help', '牙齿护理对易积累牙垢的小型梗犬很重要；洁齿零食和刷牙有帮助'],
  ['Feed twice daily on a schedule rather than free-feeding to support an active lifestyle', '按时每天两餐而非自由取食，支持活跃的生活方式'],
  ['DHA-rich food or supplement to support exceptional cognitive function', '富含DHA的食物或补充剂，支持卓越的认知功能'],
  ['Mental enrichment snacks (puzzle feeders, lick mats) to engage their brain at mealtimes', '心理丰容零食（益智喂食器、舔食垫）在进餐时激活其大脑'],
  ['Elevated feeders may reduce bloat risk for some giant breeds', '高脚喂食器可能降低某些巨型犬种的胃扩张风险'],
  ['Monitor weight — thin flanks are normal for the breed, but ribs should not be sharply protruding', '监控体重——腰部纤细对该犬种是正常的，但肋骨不应明显突出'],
  ['The rough beard and mustache trap food and water — clean after meals to prevent odor and skin irritation', '粗糙的胡须和髭须会沾染食物和水——进餐后清洁以防止异味和皮肤刺激'],
  ['Avoid grain-free diets with legumes as the main ingredient — Boxers have a higher-than-average rate of heart disease (ARVC), and legume-heavy foods may compound cardiac risk', '避免以豆类为主要成分的无谷物饮食——拳师犬心脏病（ARVC）发病率高于平均水平，豆类为主的食物可能增加心脏风险'],
  ['Split meals into 2 per day minimum — Boxers are deep-chested and prone to life-threatening bloat (GDV)', '每天至少分成2餐——拳师犬胸部深且易患危及生命的胃扩张（GDV）'],
  ['Avoid vigorous exercise for at least 60 minutes after eating — this is especially critical for the Boxer', '进食后至少60分钟内避免剧烈运动——这对拳师犬尤为重要'],
  ['Ear cleaning after water activities reduces infection risk', '水上活动后清洁耳道降低感染风险'],
  ['Avoid high-calorie diets in the off-season — they gain weight easily when inactive', '淡季避免高热量饮食——不活跃时容易增重'],
  ['Feed 2 smaller meals rather than one large meal to reduce bloat risk in this deep-chested breed', '每天2次较小份量喂食，而非一次大量喂食，以降低这一深胸犬种的胃扩张风险'],
  ['Joint-supporting supplements (glucosamine, chondroitin) beneficial given hip dysplasia prevalence', '关节支持补充剂（葡萄糖胺、软骨素）有益，考虑到髋关节发育不良的普遍性'],
  ['Active hunting Braccos may need 25–50% more calories during the hunting season than during rest periods', '活跃狩猎的意大利布拉克犬在狩猎季节可能需要比休息期多25–50%的热量'],
  ['Feed twice daily to minimize bloat risk', '每天两餐以最大程度降低胃扩张风险'],
  ['Biotin supplements can support the long, wavy coat condition', '生物素补充剂可支持长而波浪状的被毛状态'],
  ['Feed twice daily on a schedule rather than free-feeding to support an active lifestyle', '按时每天两餐而非自由取食，支持活跃的生活方式'],
  ['Never overfeed — excess weight worsens breathing in this flat-faced breed', '绝不过度喂食——超重会加重这一扁脸犬种的呼吸问题'],
  ['Elevated food bowls can help reduce swallowed air in brachycephalic dogs', '高脚碗有助于减少短头犬种吞入的空气'],
  ['Given hereditary nephritis risk, high-protein diets may need monitoring — discuss with your vet if kidney issues are suspected', '考虑到遗传性肾炎风险，高蛋白饮食可能需要监测——如果怀疑肾脏问题，请与兽医讨论'],
  ['Fresh water always available', '始终提供充足饮水'],
  ['Always use a slow-feed or puzzle bowl — Bulldogs gulp food and air, which leads to gas, bloating, and digestive discomfort', '始终使用慢食碗或益智碗——斗牛犬狼吞虎咽，吃进食物和空气，导致胀气、腹胀和消化不适'],
  ['Joint supplements are important from middle age; a 130-lb dog puts enormous stress on hips and elbows over time', '中年后关节补充剂变得重要；130磅的犬只长期对臀部和肘部造成巨大压力'],
  ['Monitor weight carefully — an obese Bullmastiff faces dramatically increased joint, cardiac, and respiratory strain', '仔细监控体重——肥胖的斗牛獒面临大幅增加的关节、心脏和呼吸系统压力'],
  ['高-quality dry kibble with real meat as the first ingredient', '以真实肉类为首要成分的优质干粮'],
  ['Avoid: artificial colors, BHA/BHT preservatives, excessive corn and soy fillers', '避免：人工色素、BHA/BHT防腐剂、过多玉米和大豆填充物'],
  ['Lean body condition is natural and correct — do not overfeed to add bulk', '精瘦体型对该犬种是自然且正确的——不要过度喂食来增加重量'],
  ['Avoid free-feeding — the efficient desert metabolism can lead to rapid weight gain if food is always available', '避免自由取食——高效的沙漠型代谢在食物始终充足时会导致快速增重'],
  ['Quality protein supports the Cardigan\'s athletic herding build without overloading a short-legged frame', '优质蛋白质支持卡狄根柯基的运动型牧羊体型，而不给短腿体型增加负担'],
  ['Strictly control calories — Cardigans gain weight easily and obesity dramatically increases IVDD risk', '严格控制热量——卡狄根柯基容易增重，肥胖会大幅增加椎间盘疾病风险'],
  ['Feed twice daily and avoid post-meal exercise to protect the digestive system of a deep-chested small breed', '每天两餐，进餐后避免运动，保护深胸小型犬种的消化系统'],
  ['Dental chews or water additives — small breeds are prone to dental issues', '洁齿零食或漱口水添加剂——小型犬易患牙科问题'],
  ['Measured meals twice daily to prevent obesity', '每天两次量取份量喂食以防止肥胖'],
  ['The food-motivated Cesky responds well to treat-based training — factor treats into daily caloric totals', '食物驱动的切斯基梗对零食训练反应良好——将零食纳入每日总热量计算'],
  ['Very small breed with minimal caloric needs — overfeeding is a serious risk; measure portions precisely', '热量需求极低的极小型犬——过度喂食是严重风险；精确量取份量'],
  ['Dental-supportive diet is important — dental disease is the breed\'s 最常见 health issue', '支持牙齿健康的饮食很重要——牙科疾病是该犬种最常见的健康问题'],
  ['Warm food slightly to entice this small breed, which may be choosy about food texture and temperature', '略微温热食物以吸引这种小型犬，它们可能对食物质地和温度很挑剔'],
  ['Novel proteins (duck, venison, rabbit) reduce allergic reactions', '新型蛋白质（鸭肉、鹿肉、兔肉）减少过敏反应'],
  ['Avoid corn, wheat, and soy if skin issues are present', '如果出现皮肤问题，避免玉米、小麦和大豆'],
  ['Keep fresh water always available — Shar-Peis can overheat quickly', '始终提供充足饮水——中国沙皮犬可能迅速过热'],
  ['Glucosamine and chondroitin beneficial for hip health in this large breed', '葡萄糖胺和软骨素有益于这一大型犬种的髋关节健康'],
  ['Feed two meals daily to reduce bloat risk for this deep-chested dog', '每天两餐以降低这一深胸犬的胃扩张风险'],
  ['Avoid obesity — the Chow is a low-energy breed that easily becomes overweight without portion control', '避免肥胖——松狮犬是低能量犬种，不控制份量很容易超重'],
  ['Feed in a cool location — the dense coat makes Chow Chows heat-sensitive; heavy eating in warm weather can cause distress', '在凉爽地点喂食——浓密的被毛使松狮犬对热敏感；温暖天气中大量进食可能导致不适'],
  ['Monitor weight carefully — Clumbers gain weight easily on a sedentary lifestyle', '仔细监控体重——克伦伯猎鸟犬在久坐生活方式下容易增重'],
  ['Joint-supporting supplements (glucosamine, chondroitin) recommended given heavy build', '鉴于其沉重体型，推荐关节支持补充剂（葡萄糖胺、软骨素）'],
  ['Avoid free-feeding — measured meals twice daily prevent obesity', '避免自由取食——每天两次量取份量喂食防止肥胖'],
  ['Look for formulas with real protein (chicken, salmon) as the first ingredient', '寻找以真实蛋白质（鸡肉、三文鱼）为首要成分的配方'],
  ['Avoid high-fat treats which can contribute to pancreatitis', '避免高脂肪零食，可能导致胰腺炎'],
  ['Cockers prone to skin conditions may benefit from limited-ingredient or grain-free diets — consult your vet', '易患皮肤病的可卡犬可能受益于有限配料或无谷物饮食——请咨询兽医'],
  ['Do NOT brush the curly coat — it destroys curl structure; minimal grooming is best', '绝不梳理卷毛——会破坏卷毛结构；最少的美容是最好的'],
  ['Feed twice daily and restrict exercise around meals to reduce bloat risk', '每天两餐，进餐前后限制运动以降低胃扩张风险'],
  ['Avoid foods with excessive fat — Dachshunds are prone to pancreatitis, especially if they sneak fatty table scraps', '避免高脂肪食物——腊肠犬易患胰腺炎，尤其是偷吃含脂肪的桌上剩食时'],
  ['Monitor weight carefully in the off-season — they gain weight easily without exercise', '淡季仔细监控体重——缺乏运动时容易增重'],
  ['Do NOT add extra food to "fill them out" — visible ribs and spine are breed-normal', '不要额外添加食物"填充它们"——可见的肋骨和脊椎对该犬种是正常的'],
  ['Inform every vet treating your Azawakh of sighthound anesthesia sensitivity before any procedure', '在任何手术前告知每位治疗阿扎瓦克犬的兽医视觉猎犬的麻醉敏感性'],
  ['Feed two meals daily to reduce bloat risk in this deep-chested breed', '每天两餐以降低这一深胸犬种的胃扩张风险'],
  ['Quality protein for active sporting dog', '优质蛋白质适合活跃的运动型犬'],
  ['Joint support for water retrieval activities', '水中寻回活动的关节支持'],
  ['Antioxidants for long-term health', '抗氧化剂支持长期健康'],
  ['Monitor for Fanconi syndrome — if diagnosed, dietary protein and phosphorus levels require careful veterinary management', '监测范可尼综合征——如果诊断，饮食蛋白质和磷水平需要谨慎的兽医管理'],
  ['Feed twice daily rather than free-feeding to establish routine and monitor a Basenji\'s characteristically fussy appetite', '每天两餐而非自由取食，以建立规律并监测巴辛吉犬特有的挑食胃口'],
  ['Feed 每天2餐 — bloat risk is significant in deep-chested breeds; never exercise immediately after eating', '每天2餐——深胸犬种胃扩张风险显著；进食后立即避免运动'],
  ['Joint supplements (glucosamine, fish oil) beneficial given the breed\'s size and activity level', '关节补充剂（葡萄糖胺、鱼油）有益，考虑到犬种的体型和活动水平'],
  ['Glucosamine for joint support', '葡萄糖胺支持关节健康'],
  ['Digestive enzymes for gut health', '消化酶支持肠道健康'],
  ['Feed 每天2餐 minimum to reduce bloat risk — never feed one large meal', '每天至少2餐以降低胃扩张风险——绝不一次性大量喂食'],
  ['Split into 每天2餐 — never one large meal — to reduce the risk of bloat', '分成每天2餐——绝不一次性大量喂食——以降低胃扩张风险'],
  ['Vitamins E and C for immune support', '维生素E和C支持免疫系统'],
  ['Two meals per day reduces bloat risk', '每天两餐降低胃扩张风险'],
  ['Antioxidant-rich diet may support cancer prevention', '富含抗氧化剂的饮食可能支持癌症预防'],
  ['Sighthounds have low body fat and special anesthesia sensitivity — inform your vet', '视觉猎犬体脂低，对麻醉有特殊敏感性——告知您的兽医'],
  ['Joint support for water retrieval activities', '水中寻回活动的关节支持'],
  ['Keep fresh water always available', '始终提供充足的清洁饮水'],
  ['Two meals daily (no free-feeding) to reduce bloat risk', '每天两餐（避免自由取食）以降低胃扩张风险'],
  ['Joint supplements (glucosamine, chondroitin) help support an intensely active working dog\'s longevity', '关节补充剂（葡萄糖胺、软骨素）有助于支持高强度工作犬的长寿'],
  ['Feed after exercise, not before, to reduce bloat risk in this active but deep-chested medium breed', '运动后而非运动前喂食，以降低这一活跃但深胸中型犬种的胃扩张风险'],
  ['Joint supplements (glucosamine, fish oil) from middle age onward', '从中年开始补充关节营养素（葡萄糖胺、鱼油）'],
  ['Adjust portions based on activity level — working dogs need more', '根据活动水平调整份量——工作犬需要更多'],
  ['Highly digestible protein sources (chicken, turkey, fish) minimize GI sensitivity in this breed', '高消化率蛋白质来源（鸡肉、火鸡肉、鱼肉）最大程度减少该犬种的胃肠敏感性'],
  ['Calcium and phosphorus balance matters — supports the skeletal structure of this unique body shape', '钙磷平衡很重要——支持这种独特体型的骨骼结构'],
  ['Antioxidants for liver support', '抗氧化剂支持肝脏健康'],
  ['Never feed one large meal — always split into 2 portions to significantly reduce the risk of life-threatening bloat (GDV)', '绝不一次性大量喂食——始终分成2份以显著降低威胁生命的胃扩张（GDV）风险'],

  // ── Cost tab remaining ─────────────────────────────────────────────────────
  ['$1,500 – $2,500 (very risky)', '$1,500 – $2,500（风险极高）'],
  ['$200 – $600 (risky)', '$200 – $600（有风险）'],
  ['$300 – $600 (risky)', '$300 – $600（有风险）'],
  ['$300 – $700 (risky)', '$300 – $700（有风险）'],
  ['$300 – $800 (risky)', '$300 – $800（有风险）'],
  ['$400 – $800 (risky)', '$400 – $800（有风险）'],
  ['$400 – $900 (risky)', '$400 – $900（有风险）'],
  ['$500 – $1,000 (risky)', '$500 – $1,000（有风险）'],
  ['$500 – $1,200 (risky)', '$500 – $1,200（有风险）'],
  ['$800 – $1,500 (risky)', '$800 – $1,500（有风险）'],
  ['$200 – $500 (very risky)', '$200 – $500（风险极高）'],
];

const zhDir = path.join(__dirname, 'zh', 'breeds');
const files = fs.readdirSync(zhDir).filter(f => f.endsWith('.html') && f !== 'index.html');

let totalReplacements = 0;
let filesChanged = 0;

for (const file of files) {
  const filePath = path.join(zhDir, file);
  let html = fs.readFileSync(filePath, 'utf8');
  const original = html;

  for (const [en, zh] of REPLACEMENTS) {
    if (html.includes(en)) {
      html = html.split(en).join(zh);
      totalReplacements++;
    }
  }

  if (html !== original) {
    fs.writeFileSync(filePath, html, 'utf8');
    filesChanged++;
  }
}

console.log(`Files changed: ${filesChanged}, Total replacement instances: ${totalReplacements}`);
