/**
 * Translates 别名 (nickname/alias) values in all Chinese breed HTML pages.
 * Run: node translate_aliases.js
 */
const fs = require('fs');
const path = require('path');

// breed slug → Chinese alias string
const ALIAS_MAP = {
  'affenpinscher': '猴子梗, 猴脸犬',
  'affenpoo': '非凡贵宾犬',
  'afghan-hound': '阿富汗猎犬, 阿富汗',
  'airedale-terrier': '梗犬之王, 水边梗',
  'airedoodle': '艾尔代尔贵宾犬',
  'akita-shepherd': '秋田牧羊犬',
  'akita': '秋田, 日本秋田犬',
  'alaskan-malamute': '阿拉斯加, 马拉穆特',
  'american-english-coonhound': '英式浣熊猎犬, 红斑浣熊猎犬',
  'american-eskimo-dog': '爱斯基摩犬, Eskie',
  'american-foxhound': '弗吉尼亚猎狐犬, 美式猎犬',
  'american-hairless-terrier': 'AHT',
  'american-staffordshire-terrier': 'AmStaff, 美国斯塔福德梗',
  'american-water-spaniel': 'AWS, 美国水猎犬',
  'anatolian-shepherd-dog': '康加尔牧羊犬, Coban Köpeği, 土耳其牧羊犬',
  'aussiedoodle': '澳式贵宾犬, 澳牧贵宾',
  'aussiedor': '澳牧拉多',
  'australian-cattle-dog': '蓝色跟腱犬, 红色跟腱犬, 昆士兰跟腱犬, ACD',
  'australian-shepherd': '澳牧',
  'australian-terrier': '澳梗',
  'azawakh': 'Idi, Hanshee, Oska, Rawondu（非洲原名）',
  'bagel-hound': '比格巴吉度混血',
  'barbet': '法国水猎犬',
  'basenji': '非洲无吠犬, 刚果犬, 赞德犬',
  'bassador': '巴吉度拉多',
  'basset-hound': '巴吉度',
  'beabull': '比格斗牛混血',
  'beagador': '比格拉多',
  'beagle': '英国比格犬, 猎兔犬',
  'beaglier': '比格骑士混血',
  'bearded-collie': '有胡须的柯利, Beardie',
  'beauceron': '博斯牧羊犬, Bas Rouge, 法国短毛牧羊犬',
  'bedlington-terrier': '贝灵顿梗, 羊羔犬',
  'belgian-laekenois': '拉肯诺斯犬, 比利时麻布被毛牧羊犬',
  'belgian-malinois': '马里诺斯犬, 马里',
  'belgian-sheepdog': '格罗恩达尔犬, 比利时黑色长毛牧羊犬',
  'belgian-tervuren': '特伏丹犬, 比利时长毛牧羊犬',
  'bergamasco-sheepdog': '贝加马斯科牧羊犬, Cane da pastore bergamasco',
  'berger-picard': '皮卡第牧羊犬, 法国卡第牧羊犬',
  'bernedoodle': '伯恩山贵宾犬',
  'bernese-mountain-dog': '伯纳犬, Berner Sennenhund',
  'bichon-frise': 'Bichon à poil frisé, 特内里费犬',
  'biewer-terrier': 'Biewer约克夏梗, Biewer à la Pom Pon',
  'black-and-tan-coonhound': 'B&T, 美国黑褐浣熊猎犬',
  'black-russian-terrier': '黑珍珠, 俄罗斯黑色梗犬',
  'bloodhound': '寻血猎犬, 比利时圣于贝尔犬',
  'bluetick-coonhound': '蓝斑浣熊猎犬',
  'boerboel': '南非獒犬, 布尔犬',
  'borador': '博德拉多犬',
  'border-collie': '苏格兰牧羊犬, 博德柯利',
  'border-terrier': 'BT, 科克代尔梗, 里德沃特梗',
  'bordoodle': '边牧贵宾犬',
  'borzoi': '俄国猎狼犬, 俄国灵缇',
  'bossipoo': '波士顿贵宾混血',
  'boston-terrier': '美国绅士',
  'bouvier-des-flandres': '比利时牧牛犬, Vuilbaard（脏胡子）',
  'boxador': '拳师拉多犬',
  'boxer': '拳师犬, Deutscher Boxer',
  'boxerdoodle': '拳师贵宾犬',
  'boykin-spaniel': '博伊金猎鸟犬, 南卡罗来纳州犬',
  'bracco-italiano': '意大利指示犬, 意大利布拉克',
  'briard': '法国长毛牧羊犬, 法国绵羊犬',
  'brittany': '布列塔尼猎鸟犬, Épagneul Breton',
  'brussels-griffon': '布鲁塞尔格里芬犬, 格里芬贝尔奇',
  'bugg': '波士顿巴哥混血',
  'bull-terrier': '斗牛梗, 英国斗牛梗',
  'bullador': '斗牛拉多犬',
  'bulldog': '英国斗牛犬, 英式斗牛犬',
  'bullmastiff': '猎场看守犬, 斗牛獒',
  'cairn-terrier': '凯恩梗, 刷地梗',
  'cairnoodle': '凯恩贵宾犬',
  'canaan-dog': 'Kelev Kna\'ani（希伯来语）, 以色列国犬',
  'cane-corso': '意大利獒犬, Cane Corso Italiano',
  'cardigan-welsh-corgi': '卡狄根柯基, CWC, 码长犬（历史称谓）',
  'cavalier-king-charles': '骑士查理王猎鸟犬, CKCS',
  'cavachon': '骑士双飞犬',
  'cavapoo': '骑士贵宾犬, Cavoodle',
  'cavapoochon': '骑士贵宾双飞混血',
  'cesky-terrier': '波西米亚梗, 捷克梗',
  'cheagle': '吉娃娃比格混血',
  'chesapeake-bay-retriever': '切萨皮克湾寻回犬, Chessie',
  'chihuahua': '吉娃娃, Chi',
  'chinese-crested': '冠毛犬, 中国冠毛无毛犬, 粉扑犬',
  'chinese-shar-pei': '沙皮犬, 中国沙皮',
  'chinook': '美国雪橇犬, 西努克',
  'chipoo': '吉娃娃贵宾犬',
  'chiweenie': '吉娃娃腊肠混血',
  'chow-chow': '松狮犬, 松狮, 唐犬',
  'chow-shepherd': '松狮牧羊混血',
  'chug': '吉娃娃巴哥混血',
  'chusky': '松狮哈士奇混血',
  'cirneco-dell-etna': '西西里灵缇, 西西里猎犬',
  'clumber-spaniel': '克伦伯猎鸟犬, 绅士猎鸟犬',
  'cockapoo': '可卡贵宾犬, Cockerdoodle',
  'cocker-spaniel': '可卡犬, 美国可卡',
  'collie': '粗毛柯利, 灵犬莱西',
  'corgi': '彭布罗克柯基, 威尔士柯基',
  'corgidor': '柯基拉多混血',
  'corgipoo': '柯基贵宾混血',
  'corman-shepherd': '柯基德牧混血',
  'coton-de-tulear': '棉花犬, 马达加斯加皇家犬',
  'curly-coated-retriever': '卷毛寻回犬, CCR',
  'dachshund': '腊肠犬, 香肠犬, Teckel, Dackel',
  'dalmadoodle': '斑点贵宾犬',
  'dalmatian': '马车犬, 斑点犬, 消防狗',
  'dandie-dinmont-terrier': '丹迪·丁蒙梗, 欣德利梗',
  'danish-swedish-farmdog': '丹麦瑞典农场犬',
  'doberdoodle': '杜宾贵宾犬',
  'doberman-pinscher': '杜宾犬, Dobie',
  'dogo-argentino': '阿根廷獒犬, 阿根廷斗狗',
  'dogue-de-bordeaux': '法国獒犬, 波尔多斗牛犬, DDB',
  'dorgi': '腊肠柯基混血',
  'double-doodle': '双拼贵宾犬',
  'doxiepoo': '腊肠贵宾混血',
  'english-cocker-spaniel': '英国可卡犬, ECS',
  'english-foxhound': '英国猎狐犬',
  'english-setter': '拉弗拉克雪达犬, 卢埃林雪达犬（田野型）',
  'english-springer-spaniel': '史宾格犬, ESS',
  'english-toy-spaniel': '查理王猎鸟犬, 查理王',
  'entlebucher-mountain-dog': '恩特雷布赫山地犬, Entle',
  'field-spaniel': '田野猎鸟犬',
  'finnish-lapphund': '芬兰拉普猎犬',
  'finnish-spitz': '芬兰猎鸟犬, 芬兰吠叫犬, Finkie',
  'flandoodle': '弗兰德贵宾犬',
  'flat-coated-retriever': '平毛寻回犬, 彼得·潘犬',
  'foodle': '猎狐梗贵宾混血',
  'frenchton': '法斗波士顿混血',
  'french-bulldog': '法斗, 法国斗牛犬',
  'froodle': '法斗贵宾混血',
  'gerberian-shepsky': '德牧哈士奇混血',
  'german-pinscher': '德国宾沙犬',
  'german-shepherd': 'GSD, 阿尔萨斯犬, 德国牧羊犬',
  'german-shorthaired-pointer': 'GSP, 德国短毛指示犬',
  'german-wirehaired-pointer': 'GWP, Deutsch Drahthaar, 德国钢毛指示犬',
  'giant-schnauzer': '巨型雪纳瑞, 慕尼黑雪纳瑞',
  'glen-of-imaal-terrier': '格伦梗, 威克洛梗, 爱尔兰格伦梗',
  'goberian': '金毛哈士奇混血',
  'goldador': '金毛拉多混血',
  'golden-mountain-dog': '金毛伯恩山混血',
  'golden-retriever': '金毛寻回犬, 金色, 金毛',
  'gollie': '金毛柯利混血',
  'goldendoodle': '黄金贵宾犬, Groodle',
  'gordon-setter': '戈登雪达犬, 黑褐雪达犬',
  'goldmaraner': '金毛威玛混血',
  'grand-basset-griffon-vendeen': '大格里芬旺代巴吉度, GBGV',
  'great-dane': '大丹犬, 德国獒犬, 犬中阿波罗',
  'great-danoodle': '大丹贵宾混血',
  'great-pyrenees': '大白熊犬, 比利牛斯山犬, Patou',
  'greater-swiss-mountain-dog': '大瑞士山地犬, Swissie',
  'greyhound': '灵缇犬, 英国灵缇',
  'harrier': '哈利犬, 野兔猎犬',
  'havapoo': '哈瓦那贵宾混血',
  'havanese': '哈瓦那犬, 哈瓦那丝绒犬',
  'horgi': '哈士奇柯基混血',
  'huskimo': '哈士奇爱斯基摩混血',
  'huskydoodle': '哈士奇贵宾混血',
  'husky-inu': '哈士奇柴犬混血',
  'ibizan-hound': '伊比沙猎犬, Podenco Ibicenco',
  'icelandic-sheepdog': '冰岛牧羊犬, Íslenskur fjárhundur',
  'irish-doodle': '爱尔兰雪达贵宾混血',
  'irish-red-and-white-setter': '爱尔兰红白雪达犬',
  'irish-setter': '爱尔兰雪达犬, 爱尔兰红色雪达犬',
  'irish-terrier': '爱尔兰梗, 红色魔鬼',
  'irish-water-spaniel': '爱尔兰水猎犬, 鞭尾犬, IWS',
  'irish-wolfadoodle': '爱尔兰猎狼贵宾混血',
  'irish-wolfhound': '爱尔兰猎狼犬, IWH',
  'italian-greyhound': '意大利灵缇, IG',
  'jackadoodle': '杰克罗素贵宾混血',
  'japanese-chin': '狆, 日本狆犬',
  'jug': '杰克罗素巴哥混血',
  'keeshond': '荷兰狮毛犬, 荷兰卷尾犬',
  'kerry-blue-terrier': '凯利蓝梗, 爱尔兰蓝梗',
  'komondor': '科蒙多尔犬, 匈牙利绳状毛犬',
  'kuvasz': '匈牙利库瓦兹犬',
  'labmaraner': '拉多威玛混血',
  'labsky': '拉多哈士奇混血',
  'labradoodle': '拉布拉多贵宾犬, Doodle',
  'labrador-retriever': '拉布拉多犬, 拉布拉多',
  'lagotto-romagnolo': '罗马涅水猎犬, 意大利松露犬',
  'lakeland-terrier': '莱克兰梗',
  'lancashire-heeler': '奥姆斯柯克跟腱犬, 兰开夏跟腱犬',
  'leonberger': '莱昂贝格犬, 狮子犬',
  'lhasa-apso': '拉萨阿普索, 西藏圣犬',
  'lhasapoo': '拉萨贵宾混血',
  'lowchen': '小狮子犬, Petit Chien Lion',
  'maltichon': '马耳他双飞混血',
  'manchester-terrier': '黑褐梗, 绅士梗',
  'malshi': '马耳他西施混血',
  'maltese': '马耳他犬, 马耳他狮子犬',
  'maltipoo': '马耳他贵宾犬, Maltepoo',
  'mastiff': '英国獒犬, 老虎犬',
  'mastidoodle': '獒犬贵宾混血',
  'miniature-american-shepherd': '迷你澳牧, MAS',
  'miniature-bull-terrier': '迷你斗牛梗, MBT',
  'miniature-pinscher': '迷你宾沙犬, Min Pin, 小杜宾',
  'miniature-schnauzer': '迷你雪纳瑞, Zwergschnauzer',
  'morkie': '马耳他约克夏混血',
  'mudi': '匈牙利穆迪犬',
  'neapolitan-mastiff': '那不勒斯獒犬, Neo, 意大利獒犬',
  'nederlandse-kooikerhondje': '荷兰诱鸭猎鸟犬, Kooiker',
  'newfiedoodle': '纽芬兰贵宾混血',
  'newfoundland': '纽芬兰犬, Newf, 温柔巨犬',
  'norfolk-terrier': '诺福克梗',
  'norwegian-buhund': '挪威布哈德犬, 挪威牧羊犬',
  'norwegian-elkhound': '挪威猎麋犬, 灰色挪威猎麋',
  'norwegian-lundehund': '海雀犬, 挪威隆德猎犬',
  'norwich-terrier': '诺里奇梗',
  'nova-scotia-duck-tolling-retriever': '托勒犬, NSDR, 小河鸭猎犬',
  'old-english-sheepdog': '古英格兰牧羊犬, OES, 毛毛熊犬',
  'otterhound': '水獭猎犬, OH',
  'papillon': '蝴蝶犬, 蛾眉犬',
  'parson-russell-terrier': '帕森罗素梗, PRT',
  'peekapoo': '博美京叭贵宾混血',
  'pekingese': '北京犬, 京巴, 狮子犬',
  'petit-basset-griffon-vendeen': '小格里芬旺代巴吉度, PBGV',
  'pharaoh-hound': '法老猎犬, Kelb tal-Fenek',
  'pitsky': '比特斗牛哈士奇混血',
  'plott-hound': '普洛特猎犬',
  'pointer': '英国指示犬',
  'polish-lowland-sheepdog': '波兰低地牧羊犬, PON',
  'pom-a-pug': '博美巴哥混血',
  'pomapoo': '博美贵宾混血',
  'pomchi': '博美吉娃娃混血',
  'poochon': '贵宾双飞混血',
  'pooton': '贵宾棉花混血',
  'portidoodle': '葡萄牙水犬贵宾混血',
  'pomsky': '博美哈士奇混血',
  'pomeranian': '博美犬, 博美, 玩具德国斯皮茨',
  'poodle': '贵宾犬, Caniche',
  'portuguese-podengo-pequeno': '葡萄牙小波登格犬, PPP',
  'portuguese-water-dog': '葡萄牙水犬, PWD',
  'pugapoo': '巴哥贵宾混血',
  'puggle': '巴哥比格混血',
  'pug': '巴哥犬, 荷兰斗牛犬, Mops',
  'puli': '普利犬, 匈牙利绳状被毛牧羊犬',
  'pumi': '匈牙利普米犬, 匈牙利牧羊梗',
  'pyredoodle': '大白熊贵宾混血',
  'pyrenean-shepherd': '比利牛斯牧羊犬, Pyr Shep',
  'rat-terrier': '鼠梗, 美国鼠梗',
  'ratoodle': '鼠梗贵宾混血',
  'redbone-coonhound': '红骨猎浣熊犬, Redbone',
  'rhodesian-ridgeback': '罗得西亚脊背犬, 狮子猎犬',
  'rottador': '罗威纳拉多混血',
  'rottsky': '罗威纳哈士奇混血',
  'rottweiler': '罗威纳犬, Rottie',
  'rottle': '罗威纳贵宾混血',
  'russell-terrier': '杰克罗素梗, 短腿JRT',
  'saint-berdoodle': '圣伯纳贵宾混血',
  'saint-bernard': '圣伯纳犬, 阿尔卑斯救援犬',
  'saluki': '萨路基猎犬, 波斯灵缇, 皇家猎犬',
  'sammypoo': '萨摩贵宾混血',
  'samoyed': '萨摩耶犬, 微笑天使',
  'schipperke': '小船长犬, 小舟人',
  'scoodle': '苏格兰梗贵宾混血',
  'scottish-deerhound': '苏格兰猎鹿犬',
  'scottish-terrier': '苏格兰梗, Scottie',
  'sealyham-terrier': '西利汉梗, Sealy',
  'sheepadoodle': '英国牧羊贵宾混血',
  'shepadoodle': '德牧贵宾混血',
  'sheprador': '德牧拉多混血',
  'shiba-inu': '柴犬, 小灌木丛犬',
  'shih-poo': '西施贵宾混血',
  'silky-terrier': '澳大利亚丝毛梗, 悉尼丝毛犬',
  'skye-terrier': '史凯梗, 史凯岛梗',
  'sloughi': '阿拉伯灵缇, 北非灵缇',
  'smooth-fox-terrier': '光滑短毛猎狐梗',
  'soft-coated-wheaten-terrier': '爱尔兰软毛梗, 麦色梗',
  'spanish-water-dog': '西班牙水犬',
  'spinone-italiano': '意大利格里芬犬, 意大利钢毛指示犬',
  'spoodle': '英可卡贵宾混血',
  'springerdoodle': '史宾格贵宾混血',
  'staffordshire-bull-terrier': '斯塔福德斗牛梗, Staffy, 保姆犬',
  'standard-schnauzer': '标准雪纳瑞, 中型雪纳瑞',
  'sussex-spaniel': '苏塞克斯猎鸟犬',
  'swedish-vallhund': '瑞典牧牛犬, 维京犬, Västgötaspets',
  'tibetan-mastiff': '藏獒',
  'tibetan-spaniel': '西藏猎鸟犬, 藏猎犬',
  'tibetan-terrier': '藏梗, 西藏圣犬, 多奇阿普索',
  'toy-fox-terrier': '玩具猎狐梗, TFT',
  'treeing-walker-coonhound': '沃克浣熊猎犬, TWC',
  'vizsla': '匈牙利指示犬, Magyar Vizsla',
  'weimaraner': '灰色幽灵, 威玛猎犬',
  'weimardoodle': '威玛贵宾混血',
  'welsh-springer-spaniel': '威尔士史宾格犬, Welshie',
  'welsh-terrier': '威尔士梗, Welshie',
  'west-highland-white-terrier': '西高地白梗, Westie',
  'westiepoo': '西高地贵宾混血',
  'whippet': '惠比特犬, 小灵缇',
  'whoodle': '软毛梗贵宾混血',
  'wire-fox-terrier': '刚毛猎狐梗',
  'wirehaired-pointing-griffon': '钢毛格里芬指示犬, Korthals Griffon',
  'wirehaired-vizsla': '钢毛维斯拉犬, 匈牙利钢毛指示犬',
  'woodle': '威尔士梗贵宾混血',
  'xoloitzcuintli': '肖洛犬, 墨西哥无毛犬, Xolo',
  'yorkipoo': '约克夏贵宾混血',
  'yorkshire-terrier': '约克夏梗, Yorkie',
};

const zhDir = path.join(__dirname, 'zh', 'breeds');
const files = fs.readdirSync(zhDir).filter(f => f.endsWith('.html') && f !== 'index.html');

let updated = 0;
let skipped = 0;
let notFound = [];

for (const file of files) {
  const slug = file.replace('.html', '');
  const aliasZh = ALIAS_MAP[slug];

  if (!aliasZh) {
    notFound.push(slug);
    continue;
  }

  const filePath = path.join(zhDir, file);
  const html = fs.readFileSync(filePath, 'utf8');

  // Match current alias value (any content)
  const pattern = /<div class="info-box-label">别名<\/div><div class="info-box-value">([^<]*)<\/div>/;
  const match = html.match(pattern);

  if (!match) {
    skipped++;
    continue;
  }

  const filled = html.replace(
    pattern,
    `<div class="info-box-label">别名</div><div class="info-box-value">${aliasZh}</div>`
  );

  fs.writeFileSync(filePath, filled, 'utf8');
  updated++;
}

console.log(`Updated: ${updated}, No alias box found: ${skipped}, No map entry: ${notFound.length}`);
if (notFound.length) console.log('Missing from map:', notFound.join(', '));
